<style>
@import url('https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400&family=DM+Sans:opsz,wght@9..40,300;9..40,400;9..40,500&display=swap');
</style>

<div style="box-sizing:border-box;width:95%;background:#2C2825;border-radius:14px;position:relative;overflow:hidden;font-family:'DM Sans',sans-serif;min-height:480px;display:flex;align-items:center;">
  <div style="position:absolute;inset:0;background:radial-gradient(ellipse 55% 80% at 90% 50%,rgba(196,168,130,0.12) 0%,transparent 65%);pointer-events:none;"></div>
  <div style="position:absolute;right:18%;top:10%;bottom:10%;width:1px;background:linear-gradient(to bottom,transparent,rgba(196,168,130,0.18),transparent);"></div>
  <div style="padding:4.5rem 4rem;position:relative;z-index:1;max-width:760px;">
    <p style="font-size:12px;letter-spacing:.25em;text-transform:uppercase;color:#C4A882;margin:0 0 1.2rem;font-weight:500;">Dataset · Análisis exploratorio</p>
    <h1 style="font-family:'Playfair Display',serif;font-size:3.6rem;font-weight:400;color:#FAF7F2;line-height:1.2;margin:0 0 1.6rem;border:none;padding:0;">Dataset de Predicción de Lesiones en Fútbol Universitario</h1>
    <p style="font-size:17px;color:#9E9790;line-height:1.8;margin:0 0 2.2rem;font-weight:300;">Datos completos de 800 jugadores de fútbol universitario chinos que participan en ligas universitarias y provinciales. El objetivo es predecir si un jugador sufrirá una lesión en el próximo curso académico mediante métodos de clasificación de aprendizaje automático.</p>
    <div style="display:flex;gap:.6rem;flex-wrap:wrap;">
      <span style="font-size:11px;letter-spacing:.12em;text-transform:uppercase;font-weight:500;color:#A8896A;background:rgba(196,168,130,0.1);border:1px solid rgba(196,168,130,0.22);border-radius:20px;padding:.35em 1em;">800 jugadores</span>
      <span style="font-size:11px;letter-spacing:.12em;text-transform:uppercase;font-weight:500;color:#A8896A;background:rgba(196,168,130,0.1);border:1px solid rgba(196,168,130,0.22);border-radius:20px;padding:.35em 1em;">Ligas universitarias</span>
      <span style="font-size:11px;letter-spacing:.12em;text-transform:uppercase;font-weight:500;color:#A8896A;background:rgba(196,168,130,0.1);border:1px solid rgba(196,168,130,0.22);border-radius:20px;padding:.35em 1em;">China</span>
    </div>
  </div>
</div>

Este análisis nace de una pregunta sencilla: **¿qué factores hacen que un jugador de fútbol universitario se lesione?** A lo largo de este notebook exploraremos los datos desde cero; desde cargarlos y limpiarlos, hasta construir categorías que nos permitan visualizar patrones claros. El resultado es un recorrido estructurado en cinco dimensiones: demografía, carga de entrenamiento, condición física, rendimiento neuromuscular y estilo de vida.

##
<style>
@import url('https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400&family=DM+Sans:opsz,wght@9..40,300;9..40,400;9..40,500&display=swap');
</style>

<div style="box-sizing:border-box;width:95%;background:#2C2825;border-radius:10px;position:relative;overflow:hidden;font-family:'DM Sans',sans-serif;display:flex;align-items:center;gap:1.5rem;padding:1.6rem 2.5rem;">
  <div style="position:absolute;inset:0;background:radial-gradient(ellipse 40% 120% at 100% 50%,rgba(196,168,130,0.1) 0%,transparent 65%);pointer-events:none;"></div>
  <span style="font-family:'Playfair Display',serif;font-size:3rem;font-weight:400;color:rgba(196,168,130,0.2);line-height:1;flex-shrink:0;position:relative;z-index:1;">01</span>
  <div style="width:1px;height:36px;background:rgba(196,168,130,0.2);flex-shrink:0;position:relative;z-index:1;"></div>
  <div style="position:relative;z-index:1;">
    <p style="font-size:10px;letter-spacing:.22em;text-transform:uppercase;color:#C4A882;margin:0 0 .25rem;font-weight:500;">Paso 1</p>
    <h2 style="font-family:'Playfair Display',serif;font-size:1.55rem;font-weight:400;color:#FAF7F2;margin:0;padding:0;border:none;line-height:1.2;">Importar librerías y cargar datos</h2>
  </div>
</div>

*En este primer paso preparamos el entorno de trabajo y traemos los datos al análisis. Para ello cargamos pandas, la herramienta estándar de análisis de datos en Python, que nos permite trabajar con tablas de información de forma rápida y eficiente. Sin esto, nada de lo que viene después sería posible.*

Para poder trabajar con los datos, primero cargamos las herramientas necesarias

In [152]:
%pip install pandas
import pandas as pd

Requirement already satisfied: pandas in ./.venv/lib/python3.13/site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in ./.venv/lib/python3.13/site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

A continuación, importamos el archivo que contiene la información de los jugadores. A partir de este momento, todos los datos están disponibles para ser analizados.

In [153]:
df_csv = pd.read_csv('./data/data.csv')
df_csv

,Age,Height_cm,Weight_kg,Position,Training_Hours_Per_Week,Matches_Played_Past_Season,Previous_Injury_Count,Knee_Strength_Score,Hamstring_Flexibility,Reaction_Time_ms,Balance_Test_Score,Sprint_Speed_10m_s,Agility_Score,Sleep_Hours_Per_Night,Stress_Level_Score,Nutrition_Quality_Score,Warmup_Routine_Adherence,Injury_Next_Season,BMI
0,22,NaN,64,Midfielder,11.575308,36,1,77.460279,79.115738,284.487853,91.212476,5.874630,77.599705,8.238293,46.616415,81.472206,1,0,21.383942
1,18,170.0,67,Midfielder,12.275869,37,2,72.634442,82.541688,250.579249,87.294078,5.796269,94.418987,8.983737,49.368037,81.056677,1,0,23.183391
2,22,186.0,75,Forward,12.254896,12,2,77.064490,75.943631,269.119918,83.440688,5.731209,70.179176,7.229193,43.132808,64.877457,0,1,21.678807
3,20,172.0,62,Defender,9.006678,11,1,82.810232,73.878324,226.376412,87.591894,6.220212,83.473824,7.681029,51.528529,89.824744,1,0,20.957274
4,18,172.0,94,Midfielder,12.683668,10,2,76.772859,76.653043,229.021042,83.125161,5.385958,87.037256,6.728091,52.379718,71.569197,0,1,31.773932
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,22,182.0,63,Goalkeeper,10.624037,33,1,72.678400,84.620355,240.117111,74.372627,5.789511,78.812645,7.631547,70.472112,78.795865,0,1,19.019442
796,21,181.0,66,Defender,9.732842,11,2,67.290644,70.726745,260.341118,85.392132,5.591874,81.302513,7.676296,67.209293,79.008597,1,1,20.145905
797,24,182.0,75,Goalkeeper,5.494318,17,3,81.164089,83.486771,264.192657,84.031046,5.466771,69.857954,6.798035,78.213353,74.379626,0,1,22.642193
798,20,188.0,86,Goalkeeper,10.303923,35,1,71.184901,85.585050,204.446478,84.417342,6.543996,73.459174,8.846476,50.906356,70.320367,1,0,24.332277
799,22,186.0,73,Midfielder,9.815368,15,1,59.709613,72.966692,255.770337,84.186100,5.879201,67.491525,8.109630,65.504117,68.115949,0,1,21.100705

##
<style>
@import url('https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400&family=DM+Sans:opsz,wght@9..40,300;9..40,400;9..40,500&display=swap');
</style>

<div style="box-sizing:border-box;width:95%;background:#2C2825;border-radius:10px;position:relative;overflow:hidden;font-family:'DM Sans',sans-serif;display:flex;align-items:center;gap:1.5rem;padding:1.6rem 2.5rem;">
  <div style="position:absolute;inset:0;background:radial-gradient(ellipse 40% 120% at 100% 50%,rgba(196,168,130,0.1) 0%,transparent 65%);pointer-events:none;"></div>
  <span style="font-family:'Playfair Display',serif;font-size:3rem;font-weight:400;color:rgba(196,168,130,0.2);line-height:1;flex-shrink:0;position:relative;z-index:1;">02</span>
  <div style="width:1px;height:36px;background:rgba(196,168,130,0.2);flex-shrink:0;position:relative;z-index:1;"></div>
  <div style="position:relative;z-index:1;">
    <p style="font-size:10px;letter-spacing:.22em;text-transform:uppercase;color:#C4A882;margin:0 0 .25rem;font-weight:500;">Paso 2</p>
    <h2 style="font-family:'Playfair Display',serif;font-size:1.55rem;font-weight:400;color:#FAF7F2;margin:0;padding:0;border:none;line-height:1.2;">Exploración inicial de los datos (EDA)</h2>
  </div>
</div>

*En esta segunda fase nos familiarizamos con los datos antes de tocarlos. El objetivo es entender qué información tenemos, cuánta hay y si está en buen estado. Es el paso previo indispensable a cualquier análisis.*

Lo primero que queremos saber es el tamaño de nuestra muestra: cuántos jugadores incluye el dataset y cuántas variables se han registrado para cada uno. Esto nos da una idea de si tenemos suficiente información para extraer conclusiones fiables.

In [154]:
# Comprobamos el número de filas y columnas
print(df_csv.shape)
print(f"El dataset tiene {df_csv.shape[0]} filas.")
print(f"El dataset tiene {df_csv.shape[1]} columnas.")

(800, 19)
El dataset tiene 800 filas.
El dataset tiene 19 columnas.

Mostramos las primeras filas del dataset para hacernos una idea de su estructura. Podemos ver qué tipo de información recoge cada columna: edad, posición, altura, peso, horas de sueño, nivel de estrés, historial de lesiones... Cada fila representa a un jugador.

In [155]:
# Mostramos las primeras 10 filas del DataFrame
df_csv.head(10)

,Age,Height_cm,Weight_kg,Position,Training_Hours_Per_Week,Matches_Played_Past_Season,Previous_Injury_Count,Knee_Strength_Score,Hamstring_Flexibility,Reaction_Time_ms,Balance_Test_Score,Sprint_Speed_10m_s,Agility_Score,Sleep_Hours_Per_Night,Stress_Level_Score,Nutrition_Quality_Score,Warmup_Routine_Adherence,Injury_Next_Season,BMI
0,22,NaN,64,Midfielder,11.575308,36,1,77.460279,79.115738,284.487853,91.212476,5.874630,77.599705,8.238293,46.616415,81.472206,1,0,21.383942
1,18,170.0,67,Midfielder,12.275869,37,2,72.634442,82.541688,250.579249,87.294078,5.796269,94.418987,8.983737,49.368037,81.056677,1,0,23.183391
2,22,186.0,75,Forward,12.254896,12,2,77.064490,75.943631,269.119918,83.440688,5.731209,70.179176,7.229193,43.132808,64.877457,0,1,21.678807
3,20,172.0,62,Defender,9.006678,11,1,82.810232,73.878324,226.376412,87.591894,6.220212,83.473824,7.681029,51.528529,89.824744,1,0,20.957274
4,18,172.0,94,Midfielder,12.683668,10,2,76.772859,76.653043,229.021042,83.125161,5.385958,87.037256,6.728091,52.379718,71.569197,0,1,31.773932
5,23,189.0,89,Goalkeeper,10.262987,31,2,78.450720,80.927984,265.801623,81.106339,6.354870,86.418954,8.538027,39.929697,74.982476,1,0,24.915316
6,22,189.0,71,Midfielder,8.069288,5,4,63.045009,75.032030,269.099907,76.787369,6.458297,65.179995,7.339327,75.039112,65.790192,0,1,19.876263
7,23,184.0,75,Goalkeeper,6.407939,26,0,77.566677,76.947213,226.966431,93.317382,6.161460,79.260417,8.072895,25.783371,89.782578,0,0,22.152647
8,22,174.0,71,Midfielder,10.554931,23,0,78.877905,89.584501,240.745054,80.898575,6.199281,77.152290,7.661190,52.581600,78.587201,1,0,23.450918
9,23,185.0,76,Midfielder,11.899732,22,0,83.194761,82.244364,259.628161,89.077577,6.206694,90.396480,6.035505,55.049722,83.947949,1,0,22.205990

Revisamos que cada variable esté correctamente definida. Por ejemplo, que la edad esté guardada como número y no como texto, y comprobamos si hay algún dato que falte. Detectar esto ahora nos evita errores más adelante.

In [156]:
# Revisamos el nombre de las columnas, su tipo de dato y si tiene algún valor nulo
df_csv.info()

<class 'pandas.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Age                         800 non-null    int64
 1   Height_cm                   799 non-null    float64
 2   Weight_kg                   800 non-null    int64
 3   Position                    800 non-null    str
 4   Training_Hours_Per_Week     800 non-null    float64
 5   Matches_Played_Past_Season  800 non-null    int64
 6   Previous_Injury_Count       800 non-null    int64
 7   Knee_Strength_Score         800 non-null    float64
 8   Hamstring_Flexibility       800 non-null    float64
 9   Reaction_Time_ms            800 non-null    float64
 10  Balance_Test_Score          800 non-null    float64
 11  Sprint_Speed_10m_s          800 non-null    float64
 12  Agility_Score               800 non-null    float64
 13  Sleep_Hours_Per_Night       800 non-null    float64
 14  Stress_Level_Score          800 non-null    float64
 15  Nutrition_Quality_Score     800 non-null    float64
 16  Warmup_Routine_Adherence    800 non-null    int64
 17  Injury_Next_Season          800 non-null    int64
 18  BMI                         800 non-null    float64
dtypes: float64(12), int64(6), str(1)
memory usage: 118.9 KB

Obtenemos un resumen rápido de los valores de cada variable: cuál es el valor más alto y el más bajo, cuál es la media y cómo se distribuyen los datos en general. Esto nos permite detectar si hay algún valor extraño (Ejemplo edad 100 años) que pueda distorsionar el análisis.

In [157]:
# Obtemos un resumen estadístico para entender mejor los datos y detectar outliers
df_csv.describe()

,Age,Height_cm,Weight_kg,Training_Hours_Per_Week,Matches_Played_Past_Season,Previous_Injury_Count,Knee_Strength_Score,Hamstring_Flexibility,Reaction_Time_ms,Balance_Test_Score,Sprint_Speed_10m_s,Agility_Score,Sleep_Hours_Per_Night,Stress_Level_Score,Nutrition_Quality_Score,Warmup_Routine_Adherence,Injury_Next_Season,BMI
count,800.000000,799.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000
mean,21.135000,177.413016,73.235000,9.951150,22.332500,1.536250,74.933249,79.154123,249.423244,83.832337,5.949025,78.341311,7.417124,54.039342,74.382174,0.597500,0.500000,23.377364
std,1.991037,7.151748,9.929276,2.610395,10.311516,1.292584,6.672704,6.782332,22.532387,6.931657,0.329133,8.775418,0.793183,11.421143,9.324899,0.490708,0.500313,3.673279
min,18.000000,154.000000,45.000000,5.000000,5.000000,0.000000,52.391351,58.180381,180.000000,60.059484,4.862435,50.000000,5.000000,21.561186,50.000000,0.000000,0.000000,14.346326
25%,19.000000,173.000000,66.000000,8.127151,13.000000,1.000000,70.432656,74.495959,234.089585,79.044910,5.732552,72.675392,6.850062,45.775371,67.809084,0.000000,0.000000,20.786644
50%,21.000000,177.000000,73.000000,9.895710,22.000000,1.000000,74.997933,79.187909,249.127328,84.156236,5.937692,78.340973,7.424618,54.047208,74.363878,1.000000,0.500000,23.130560
75%,23.000000,182.000000,80.000000,11.535140,32.000000,2.000000,79.632391,83.813179,265.105082,88.877902,6.159205,84.093489,7.988100,61.910804,80.502613,1.000000,1.000000,26.024182
max,24.000000,200.000000,105.000000,18.866608,39.000000,8.000000,93.900051,100.000000,306.730851,100.000000,6.898228,100.000000,9.860553,87.065007,100.000000,1.000000,1.000000,36.262439

##
<style>
@import url('https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400&family=DM+Sans:opsz,wght@9..40,300;9..40,400;9..40,500&display=swap');
</style>

<div style="box-sizing:border-box;width:95%;background:#2C2825;border-radius:10px;position:relative;overflow:hidden;font-family:'DM Sans',sans-serif;display:flex;align-items:center;gap:1.5rem;padding:1.6rem 2.5rem;">
  <div style="position:absolute;inset:0;background:radial-gradient(ellipse 40% 120% at 100% 50%,rgba(196,168,130,0.1) 0%,transparent 65%);pointer-events:none;"></div>
  <span style="font-family:'Playfair Display',serif;font-size:3rem;font-weight:400;color:rgba(196,168,130,0.2);line-height:1;flex-shrink:0;position:relative;z-index:1;">03</span>
  <div style="width:1px;height:36px;background:rgba(196,168,130,0.2);flex-shrink:0;position:relative;z-index:1;"></div>
  <div style="position:relative;z-index:1;">
    <p style="font-size:10px;letter-spacing:.22em;text-transform:uppercase;color:#C4A882;margin:0 0 .25rem;font-weight:500;">Paso 3</p>
    <h2 style="font-family:'Playfair Display',serif;font-size:1.55rem;font-weight:400;color:#FAF7F2;margin:0;padding:0;border:none;line-height:1.2;">Limpieza de datos</h2>
  </div>
</div>

*Los datos del mundo real rara vez llegan perfectos. En esta sección nos aseguramos de que el dataset esté completo y sin errores antes de empezar a sacar conclusiones. Un análisis solo es tan fiable como los datos sobre los que se construye.*

Comprobamos si alguna variable tiene valores nulos; es decir, jugadores de los que no tenemos toda la información. Saber cuántos son y dónde están nos permite decidir cómo tratarlos.

In [158]:
#Sacar los valores nulos 
df_csv.isnull().sum()

Age                           0
Height_cm                     1
Weight_kg                     0
Position                      0
Training_Hours_Per_Week       0
Matches_Played_Past_Season    0
Previous_Injury_Count         0
Knee_Strength_Score           0
Hamstring_Flexibility         0
Reaction_Time_ms              0
Balance_Test_Score            0
Sprint_Speed_10m_s            0
Agility_Score                 0
Sleep_Hours_Per_Night         0
Stress_Level_Score            0
Nutrition_Quality_Score       0
Warmup_Routine_Adherence      0
Injury_Next_Season            0
BMI                           0
dtype: int64

Una vez identificado el valor nulo, localizamos exactamente qué jugador tiene ese dato incompleto. En este caso, hay un registro sin altura registrada. Al ser un único caso en una muestra amplia, la decisión más prudente es eliminarlo para no introducir incertidumbre en el análisis.

In [159]:
#Averiguar que fila es la que contiene el nulo
df_csv[df_csv['Height_cm'].isnull()]

,Age,Height_cm,Weight_kg,Position,Training_Hours_Per_Week,Matches_Played_Past_Season,Previous_Injury_Count,Knee_Strength_Score,Hamstring_Flexibility,Reaction_Time_ms,Balance_Test_Score,Sprint_Speed_10m_s,Agility_Score,Sleep_Hours_Per_Night,Stress_Level_Score,Nutrition_Quality_Score,Warmup_Routine_Adherence,Injury_Next_Season,BMI
0,22,NaN,64,Midfielder,11.575308,36,1,77.460279,79.115738,284.487853,91.212476,5.87463,77.599705,8.238293,46.616415,81.472206,1,0,21.383942

Eliminamos la fila con el dato que falta. Perder un solo registro no afecta a la representatividad del análisis, pero mantener un dato incompleto podría generar errores en los cálculos posteriores.

In [160]:
#Eliminar fila con el dato nulo 
df_csv = df_csv.dropna()
df_csv.head(5)

,Age,Height_cm,Weight_kg,Position,Training_Hours_Per_Week,Matches_Played_Past_Season,Previous_Injury_Count,Knee_Strength_Score,Hamstring_Flexibility,Reaction_Time_ms,Balance_Test_Score,Sprint_Speed_10m_s,Agility_Score,Sleep_Hours_Per_Night,Stress_Level_Score,Nutrition_Quality_Score,Warmup_Routine_Adherence,Injury_Next_Season,BMI
1,18,170.0,67,Midfielder,12.275869,37,2,72.634442,82.541688,250.579249,87.294078,5.796269,94.418987,8.983737,49.368037,81.056677,1,0,23.183391
2,22,186.0,75,Forward,12.254896,12,2,77.064490,75.943631,269.119918,83.440688,5.731209,70.179176,7.229193,43.132808,64.877457,0,1,21.678807
3,20,172.0,62,Defender,9.006678,11,1,82.810232,73.878324,226.376412,87.591894,6.220212,83.473824,7.681029,51.528529,89.824744,1,0,20.957274
4,18,172.0,94,Midfielder,12.683668,10,2,76.772859,76.653043,229.021042,83.125161,5.385958,87.037256,6.728091,52.379718,71.569197,0,1,31.773932
5,23,189.0,89,Goalkeeper,10.262987,31,2,78.450720,80.927984,265.801623,81.106339,6.354870,86.418954,8.538027,39.929697,74.982476,1,0,24.915316

Verificamos que el dataset ya no tiene ningún hueco. El resultado es cero, lo que confirma que los datos están completos e íntegros.

In [161]:
# Comprobamos que ya no hayan nulos en el data frame
totalNulos = df_csv.isnull().sum().sum()
print(f"El dataset tiene {totalNulos} nulos.")

El dataset tiene 0 nulos.

Comprobamos si existe alguna fila duplicada, si algún jugador aparece registrado más de una vez por error. Confirmamos que cada fila corresponde a un jugador único.

In [162]:
#Comprobar si hay duplicados 
df_csv.duplicated().sum()

np.int64(0)

##
<style>
@import url('https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400&family=DM+Sans:opsz,wght@9..40,300;9..40,400;9..40,500&display=swap');
</style>

<div style="box-sizing:border-box;width:95%;background:#2C2825;border-radius:10px;position:relative;overflow:hidden;font-family:'DM Sans',sans-serif;display:flex;align-items:center;gap:1.5rem;padding:1.6rem 2.5rem;">
  <div style="position:absolute;inset:0;background:radial-gradient(ellipse 40% 120% at 100% 50%,rgba(196,168,130,0.1) 0%,transparent 65%);pointer-events:none;"></div>
  <span style="font-family:'Playfair Display',serif;font-size:3rem;font-weight:400;color:rgba(196,168,130,0.2);line-height:1;flex-shrink:0;position:relative;z-index:1;">04</span>
  <div style="width:1px;height:36px;background:rgba(196,168,130,0.2);flex-shrink:0;position:relative;z-index:1;"></div>
  <div style="position:relative;z-index:1;">
    <p style="font-size:10px;letter-spacing:.22em;text-transform:uppercase;color:#C4A882;margin:0 0 .25rem;font-weight:500;">Paso 4</p>
    <h2 style="font-family:'Playfair Display',serif;font-size:1.55rem;font-weight:400;color:#FAF7F2;margin:0;padding:0;border:none;line-height:1.2;">Configuración de categorías</h2>
  </div>
</div>

*En esta sección transformamos los números en grupos con significado. Un jugador que mide 181 cm o duerme 7.2 horas no nos dice mucho por sí solo. Al agrupar a los jugadores en categorías (alto/medio/bajo, sueño óptimo/insuficiente, etc.) podemos comparar grupos entre sí y detectar patrones. Esta fase se organiza en cinco dimensiones.*

### 
<div style="box-sizing:border-box;width:95%;display:flex;align-items:center;gap:1rem;padding:.9rem 1.75rem;border-left:2px solid rgba(196,168,130,0.35);font-family:'DM Sans',sans-serif;">
  <h3 style="font-family:'Playfair Display',serif;font-size:1.5rem;font-weight:400;color:#C4A882;margin:0;padding:0;border:none;line-height:1.2;">Configuraciones iniciales</h3>
</div>

La columna que indica si un jugador se lesionó estaba etiquetada de forma confusa. La renombramos para que refleje con exactitud lo que mide: si el jugador sufrió una lesión durante la temporada que estamos analizando. Un nombre claro evita interpretaciones erróneas.

In [163]:
# Renombramos la columna Injury_Next_Season a Injury_Current_Season para nuestro mayor entendimiento del dato 
df_csv.rename(columns={'Injury_Next_Season': 'Injury_Current_Season'}, inplace=True)

Las variables que nos dicen si el jugador se lesionó y si realizó el calentamiento, estaban actualmente escritas con 0s y 1s en formato Integer. Las convertimos a formato Boolean (true y false) que nos proporciona mayor claridad semántica y mejor visualización en futuros gráficos.

In [164]:
# Transformamos "Injury_Current_Season" y "warm up routine" a booleano (valores true /false)
df_csv['Injury_Current_Season'] = df_csv['Injury_Current_Season'].astype(bool)
df_csv['Warmup_Routine_Adherence'] = df_csv['Warmup_Routine_Adherence'].astype(bool)


print (df_csv[['Warmup_Routine_Adherence', 'Injury_Current_Season']].head(10))

    Warmup_Routine_Adherence  Injury_Current_Season
1                       True                  False
2                      False                   True
3                       True                  False
4                      False                   True
5                       True                  False
6                      False                   True
7                      False                  False
8                       True                  False
9                       True                  False
10                      True                   True

### 
<div style="box-sizing:border-box;width:95%;display:flex;align-items:center;gap:1rem;padding:.9rem 1.75rem;border-left:2px solid rgba(196,168,130,0.35);font-family:'DM Sans',sans-serif;">
  <h3 style="font-family:'Playfair Display',serif;font-size:1.5rem;font-weight:400;color:#C4A882;margin:0;padding:0;border:none;line-height:1.2;">Dimensión 1: Demografía y características físicas</h3>
</div>

Dividimos a los jugadores en tres grupos según su altura (bajo, medio y alto) en relación al propio grupo. Usamos la distribución real del dataset: el tercio inferior, el central y el superior. Esto nos ayuda a simplificar el análisis, facilitar la comparación entre grupos y detectar patrones de forma más clara.

In [165]:
#Creamos una nueva columna con las nuevas categorías para "Height_cm"
df_csv['Height_category'] = ""
df_csv.head(5)

#Sacamos los percentiles 33% y 66% de "height_cm"
height33 = int(df_csv['Height_cm'].quantile(0.33))
height66 = int(df_csv['Height_cm'].quantile(0.66))
print(f'El percentil 33% es igual a {height33} cm y el el percentil 66% es igual a {height66} cm')

#Creamos las categorías para "height_cm" y añadimos los nuevos valores en la columna "Height_category"
for i in range(len(df_csv)):
    #Si el valor de cada fila en la columna "Height_cm" es menor que 174, el valor en cada fila en la columna "Height_range" será '< 174 cm'
    if df_csv.loc[df_csv.index[i], 'Height_cm'] < height33:
        df_csv.loc[df_csv.index[i], 'Height_category'] = f'< {height33} cm'

    #Si el valor de cada fila en la columna "Height_cm" es entre 174 y 180, el valor en cada fila en la columna "Height_range" será '174 - 180 cm'
    elif df_csv.loc[df_csv.index[i], 'Height_cm'] >= height33 and df_csv.loc[df_csv.index[i], 'Height_cm'] <= height66:
        df_csv.loc[df_csv.index[i], 'Height_category'] = f'{height33} - {height66} cm'

    #Si el valor de cada fila en la columna "Height_cm" es , el valor en cada fila en la columna "Height_range" será ''
    else:
        df_csv.loc[df_csv.index[i], 'Height_category'] = f'> {height66} cm'

print(df_csv['Height_category'].head(5))
df_csv.head(10)

El percentil 33% es igual a 174 cm y el el percentil 66% es igual a 180 cm
1    < 174 cm
2    > 180 cm
3    < 174 cm
4    < 174 cm
5    > 180 cm
Name: Height_category, dtype: str

,Age,Height_cm,Weight_kg,Position,Training_Hours_Per_Week,Matches_Played_Past_Season,Previous_Injury_Count,Knee_Strength_Score,Hamstring_Flexibility,Reaction_Time_ms,Balance_Test_Score,Sprint_Speed_10m_s,Agility_Score,Sleep_Hours_Per_Night,Stress_Level_Score,Nutrition_Quality_Score,Warmup_Routine_Adherence,Injury_Current_Season,BMI,Height_category
1,18,170.0,67,Midfielder,12.275869,37,2,72.634442,82.541688,250.579249,87.294078,5.796269,94.418987,8.983737,49.368037,81.056677,True,False,23.183391,< 174 cm
2,22,186.0,75,Forward,12.254896,12,2,77.064490,75.943631,269.119918,83.440688,5.731209,70.179176,7.229193,43.132808,64.877457,False,True,21.678807,> 180 cm
3,20,172.0,62,Defender,9.006678,11,1,82.810232,73.878324,226.376412,87.591894,6.220212,83.473824,7.681029,51.528529,89.824744,True,False,20.957274,< 174 cm
4,18,172.0,94,Midfielder,12.683668,10,2,76.772859,76.653043,229.021042,83.125161,5.385958,87.037256,6.728091,52.379718,71.569197,False,True,31.773932,< 174 cm
5,23,189.0,89,Goalkeeper,10.262987,31,2,78.450720,80.927984,265.801623,81.106339,6.354870,86.418954,8.538027,39.929697,74.982476,True,False,24.915316,> 180 cm
6,22,189.0,71,Midfielder,8.069288,5,4,63.045009,75.032030,269.099907,76.787369,6.458297,65.179995,7.339327,75.039112,65.790192,False,True,19.876263,> 180 cm
7,23,184.0,75,Goalkeeper,6.407939,26,0,77.566677,76.947213,226.966431,93.317382,6.161460,79.260417,8.072895,25.783371,89.782578,False,False,22.152647,> 180 cm
8,22,174.0,71,Midfielder,10.554931,23,0,78.877905,89.584501,240.745054,80.898575,6.199281,77.152290,7.661190,52.581600,78.587201,True,False,23.450918,174 - 180 cm
9,23,185.0,76,Midfielder,11.899732,22,0,83.194761,82.244364,259.628161,89.077577,6.206694,90.396480,6.035505,55.049722,83.947949,True,False,22.205990,> 180 cm
10,18,178.0,62,Forward,7.884849,29,4,78.714830,74.726306,264.047546,74.261622,6.074620,80.813247,8.287460,77.728853,63.488951,True,True,19.568236,174 - 180 cm

Aplicamos el mismo criterio con el peso: tres grupos iguales en función de cómo se distribuye el peso entre todos los jugadores. La consistencia en el método facilita comparar los resultados entre variables.

In [166]:
#Creamos una nueva columna con las nuevas categorías para "Weight_kg"
df_csv['Weight_category'] = ""
df_csv.head(5)

#Sacamos los percentiles 33% y 66% de "weight_kg"
weight33 = int(df_csv['Weight_kg'].quantile(0.33))
weight66 = int(df_csv['Weight_kg'].quantile(0.66))
print(f'El percentil 33% es igual a {weight33} kg y el el percentil 66% es igual a {weight66} kg')

#Creamos las categorías para "Weight_kg" y añadimos los nuevos valores en la columna "Weight_category"
for i in range (len(df_csv)):
    #Si el valor de cada fila en la columna "Weight_kg" es menor que 69, el valor en cada fila en la columna "Weight_category" será '< 69 kg'
    if df_csv.loc[df_csv.index[i],'Weight_kg'] < weight33:
        df_csv.loc[df_csv.index[i],'Weight_category'] = f'< {weight33} kg'

    #Si el valor de cada fila en la columna "Weight_kg" es entre 69 y 78 kg, el valor en cada fila en la columna "Weight_category" será '69 - 78 kg'
    elif df_csv.loc[df_csv.index[i],'Weight_kg'] >= weight33 and df_csv.loc[df_csv.index[i],'Weight_kg'] <= weight66:
        df_csv.loc[df_csv.index[i],'Weight_category'] = f'{weight33} - {weight66} kg'

    #Si el valor de cada fila en la columna "Weight_kg" es mayor que 77 kg, el valor en cada fila en la columna "Weight_category" será '> 78 kg'
    else:
        df_csv.loc[df_csv.index[i],'Weight_category'] = f'> {weight66} kg'
df_csv.head(5)

El percentil 33% es igual a 69 kg y el el percentil 66% es igual a 77 kg

,Age,Height_cm,Weight_kg,Position,Training_Hours_Per_Week,Matches_Played_Past_Season,Previous_Injury_Count,Knee_Strength_Score,Hamstring_Flexibility,Reaction_Time_ms,...,Sprint_Speed_10m_s,Agility_Score,Sleep_Hours_Per_Night,Stress_Level_Score,Nutrition_Quality_Score,Warmup_Routine_Adherence,Injury_Current_Season,BMI,Height_category,Weight_category
1,18,170.0,67,Midfielder,12.275869,37,2,72.634442,82.541688,250.579249,...,5.796269,94.418987,8.983737,49.368037,81.056677,True,False,23.183391,< 174 cm,< 69 kg
2,22,186.0,75,Forward,12.254896,12,2,77.064490,75.943631,269.119918,...,5.731209,70.179176,7.229193,43.132808,64.877457,False,True,21.678807,> 180 cm,69 - 77 kg
3,20,172.0,62,Defender,9.006678,11,1,82.810232,73.878324,226.376412,...,6.220212,83.473824,7.681029,51.528529,89.824744,True,False,20.957274,< 174 cm,< 69 kg
4,18,172.0,94,Midfielder,12.683668,10,2,76.772859,76.653043,229.021042,...,5.385958,87.037256,6.728091,52.379718,71.569197,False,True,31.773932,< 174 cm,> 77 kg
5,23,189.0,89,Goalkeeper,10.262987,31,2,78.450720,80.927984,265.801623,...,6.354870,86.418954,8.538027,39.929697,74.982476,True,False,24.915316,> 180 cm,> 77 kg

El BMI (Índice de Masa Corporal) se clasifica según los rangos establecidos por la Organización Mundial de la Salud: bajo peso, peso normal, sobrepeso y obesidad. A diferencia de la altura y el peso, aquí usamos una escala médica reconocida, lo que nos permite situar a los jugadores dentro de un marco de salud general.

In [167]:
#Creamos una nueva columna con las nuevas categorías para "BMI"
df_csv['Body_Mass_Index'] = ""
df_csv.head(5)

#Creamos las categorías para "BMI" y añadimos los nuevos valores en la columna "Body_Mass_Index"
for i in range (len(df_csv)):
    #Si el valor de cada fila en la columna "BMI" es menor que 18.5, el valor en cada fila en la columna "Body_Mass_Index" será 'Underweight'
    if df_csv.loc[df_csv.index[i],'BMI'] < 18.5:
        df_csv.loc[df_csv.index[i],'Body_Mass_Index'] = 'Underweight'

#Si el valor de cada fila en la columna "BMI" es entre 18.5 y 24.9, el valor en cada fila en la columna "Body_Mass_Index" será 'Normal weight'
    elif df_csv.loc[df_csv.index[i],'BMI'] >= 18.5 and df_csv.loc[df_csv.index[i],'BMI'] <= 24.9 :
        df_csv.loc[df_csv.index[i],'Body_Mass_Index'] = 'Normal weight'

#Si el valor de cada fila en la columna "BMI" es entre 24.9 y 29.9, el valor en cada fila en la columna "Body_Mass_Index" será 'Overweight'
    elif df_csv.loc[df_csv.index[i],'BMI'] >= 24.9 and df_csv.loc[df_csv.index[i],'BMI'] <= 29.9 :
        df_csv.loc[df_csv.index[i],'Body_Mass_Index'] = 'Overweight'

#Si el valor de cada fila en la columna "BMI" es mayor que 29.9, el valor en cada fila en la columna "Body_Mass_Index" será 'Obesity'
    else:
        df_csv.loc[df_csv.index[i],'Body_Mass_Index'] = 'Obesity'
 
df_csv[['Body_Mass_Index', 'BMI']].head(20)

   Body_Mass_Index        BMI
1    Normal weight  23.183391
2    Normal weight  21.678807
3    Normal weight  20.957274
4          Obesity  31.773932
5       Overweight  24.915316
6    Normal weight  19.876263
7    Normal weight  22.152647
8    Normal weight  23.450918
9    Normal weight  22.205990
10   Normal weight  19.568236
11   Normal weight  22.917610
12   Normal weight  21.499597
13   Normal weight  19.130701
14      Overweight  25.029761
15   Normal weight  22.790329
16      Overweight  26.573129
17   Normal weight  22.862369
18   Normal weight  21.007668
19   Normal weight  22.308150
20     Underweight  17.921147

### 
<div style="box-sizing:border-box;width:95%;display:flex;align-items:center;gap:1rem;padding:.9rem 1.75rem;border-left:2px solid rgba(196,168,130,0.35);font-family:'DM Sans',sans-serif;">
  <h3 style="font-family:'Playfair Display',serif;font-size:1.5rem;font-weight:400;color:#C4A882;margin:0;padding:0;border:none;line-height:1.2;">Dimensión 2: Carga de entrenamiento y competición</h3>
</div>

El dataset registraba las horas de entrenamiento por semana. Las convertimos a horas diarias asumiendo que los jugadores entrenan de lunes a viernes, ya que los partidos habitualmente se juegan en fin de semana. La carga diaria es una medida más intuitiva para analizar el esfuerzo real de cada jugador.

In [168]:
#Creamos una nueva columna con las horas de entreno diarias para "Training_Hours_Per_Week"
df_csv['Training_Hours_Per_Day'] = 0.0
df_csv.head(5)

#Asumimos que solo entrenan entre semana (Lunes a viernes) por lo tanto dividimos las horas semanales entre 5, ya que los partidos suelen ser en fin de semana
df_csv['Training_Hours_Per_Day'] = round(df_csv['Training_Hours_Per_Week']/5, 1) 

#for i in range(len(df_csv)):
    #df_csv.loc[df_csv.index[i], 'Training_Hours_Per_Day'] = round(df_csv.loc[df_csv.index[i], 'Training_Hours_Per_Week'] / 2, 1)

df_csv[['Training_Hours_Per_Day', 'Training_Hours_Per_Week']].head(10)

    Training_Hours_Per_Day  Training_Hours_Per_Week
1                      2.5                12.275869
2                      2.5                12.254896
3                      1.8                 9.006678
4                      2.5                12.683668
5                      2.1                10.262987
6                      1.6                 8.069288
7                      1.3                 6.407939
8                      2.1                10.554931
9                      2.4                11.899732
10                     1.6                 7.884849

Agrupamos a los jugadores según cuántos partidos disputaron la temporada anterior: menos de 10, entre 10 y 20, entre 20 y 30, o más de 30. Un jugador con muchos partidos acumulados puede llegar a la temporada actual con una carga histórica muy diferente a uno que apenas jugó.

In [169]:
#Creamos una nueva columna con las nuevas categorías para "Matches_Played_Past_Season"
df_csv['Matches_range_past_season'] = ""
df_csv.head(5)

#Creamos las categorías para "Matches_Played_Past_Season" y añadimos los nuevos valores en la columna "Matches_range_past_season"
for i in range (len(df_csv)):
    #Si el valor de cada fila en la columna "Matches_Played_Past_Season" es menor que 10 , el valor en cada fila en la columna "Matches_range_past_season" será 'Less than 10'
    if df_csv.loc[df_csv.index[i],'Matches_Played_Past_Season'] < 10:
        df_csv.loc[df_csv.index[i],'Matches_range_past_season'] = 'Less than 10'

#Si el valor de cada fila en la columna "Matches_Played_Past_Season" es entre 10 y 20 partidos, el valor en cada fila en la columna "Matches_range_past_season" será '10-20'
    elif df_csv.loc[df_csv.index[i],'Matches_Played_Past_Season'] >= 10 and df_csv.loc[df_csv.index[i],'Matches_Played_Past_Season'] <= 20 :
        df_csv.loc[df_csv.index[i],'Matches_range_past_season'] = '10 - 20'

#Si el valor de cada fila en la columna "Matches_Played_Past_Season" es entre 21 y 30 partidos, el valor en cada fila en la columna "Matches_range_past_season" será '21-30'
    elif df_csv.loc[df_csv.index[i],'Matches_Played_Past_Season'] >= 21 and df_csv.loc[df_csv.index[i],'Matches_Played_Past_Season'] <= 30 :
        df_csv.loc[df_csv.index[i],'Matches_range_past_season'] = '21 - 30'

#Si el valor de cada fila en la columna "Matches_Played_Past_Season" es mayor que 30 partidos, el valor en cada fila en la columna "Matches_range_past_season" será 'More than 30'
    else:
        df_csv.loc[df_csv.index[i],'Matches_range_past_season'] = 'More than 30'
df_csv.head(5)

,Age,Height_cm,Weight_kg,Position,Training_Hours_Per_Week,Matches_Played_Past_Season,Previous_Injury_Count,Knee_Strength_Score,Hamstring_Flexibility,Reaction_Time_ms,...,Stress_Level_Score,Nutrition_Quality_Score,Warmup_Routine_Adherence,Injury_Current_Season,BMI,Height_category,Weight_category,Body_Mass_Index,Training_Hours_Per_Day,Matches_range_past_season
1,18,170.0,67,Midfielder,12.275869,37,2,72.634442,82.541688,250.579249,...,49.368037,81.056677,True,False,23.183391,< 174 cm,< 69 kg,Normal weight,2.5,More than 30
2,22,186.0,75,Forward,12.254896,12,2,77.064490,75.943631,269.119918,...,43.132808,64.877457,False,True,21.678807,> 180 cm,69 - 77 kg,Normal weight,2.5,10 - 20
3,20,172.0,62,Defender,9.006678,11,1,82.810232,73.878324,226.376412,...,51.528529,89.824744,True,False,20.957274,< 174 cm,< 69 kg,Normal weight,1.8,10 - 20
4,18,172.0,94,Midfielder,12.683668,10,2,76.772859,76.653043,229.021042,...,52.379718,71.569197,False,True,31.773932,< 174 cm,> 77 kg,Obesity,2.5,10 - 20
5,23,189.0,89,Goalkeeper,10.262987,31,2,78.450720,80.927984,265.801623,...,39.929697,74.982476,True,False,24.915316,> 180 cm,> 77 kg,Overweight,2.1,More than 30

### 
<div style="box-sizing:border-box;width:95%;display:flex;align-items:center;gap:1rem;padding:.9rem 1.75rem;border-left:2px solid rgba(196,168,130,0.35);font-family:'DM Sans',sans-serif;">
  <h3 style="font-family:'Playfair Display',serif;font-size:1.5rem;font-weight:400;color:#C4A882;margin:0;padding:0;border:none;line-height:1.2;">Dimensión 3: Condición física / biomecánica</h3>
</div>

Dividimos la fuerza de rodilla en tres niveles (baja, media y alta) en relación al grupo. La fuerza de rodilla es uno de los indicadores más estudiados en la prevención de lesiones del tren inferior.

In [170]:
#Creamos una nueva columna con las nuevas categorías para "Knee_Strength_Score"
df_csv['Knee_Strength'] = ""
df_csv.head(5)

#Sacamos los percentiles 33% y 66% de "Knee_Strengh_Score"
knee33 = int(df_csv['Knee_Strength_Score'].quantile(0.33))
knee66 = int(df_csv['Knee_Strength_Score'].quantile(0.66))
print(f'El percentil 33% es igual a {knee33} y el el percentil 66% es igual a {weight66}')

#Creamos las categorías para "Knee_Strength_Score" y añadimos los nuevos valores en la columna "Knee_Strength"
for i in range (len(df_csv)):
    #Si el valor de cada fila en la columna "Knee_Strengh_Score" es menor que 72 , el valor en cada fila en la columna "Knee_Strength" será 'Weak'
    if df_csv.loc[df_csv.index[i],'Knee_Strength_Score'] < knee33:
        df_csv.loc[df_csv.index[i],'Knee_Strength'] = 'Weak'

#Si el valor de cada fila en la columna "Knee_Strengh_Score" es entre 72 y 78 partidos, el valor en cada fila en la columna "Knee_Strength" será 'Medium'
    elif df_csv.loc[df_csv.index[i],'Knee_Strength_Score'] >= knee33 and df_csv.loc[df_csv.index[i],'Knee_Strength_Score'] <= knee66 :
        df_csv.loc[df_csv.index[i],'Knee_Strength'] = 'Medium'

#Si el valor de cada fila en la columna "Knee_Strengh_Score" es mayor que 78, el valor en cada fila en la columna "Knee_Strength" será 'Strong'
    else:
        df_csv.loc[df_csv.index[i],'Knee_Strength'] = 'Strong'

df_csv[['Knee_Strength', 'Knee_Strength_Score']].head(10)

El percentil 33% es igual a 72 y el el percentil 66% es igual a 77

   Knee_Strength  Knee_Strength_Score
1         Medium            72.634442
2         Strong            77.064490
3         Strong            82.810232
4         Medium            76.772859
5         Strong            78.450720
6           Weak            63.045009
7         Strong            77.566677
8         Strong            78.877905
9         Strong            83.194761
10        Strong            78.714830

Los isquiotibiales son los músculos de la parte posterior del muslo, los más frecuentemente lesionados en el fútbol. Clasificamos su flexibilidad en tres niveles para poder comparar las tasas de lesión entre jugadores con distinta flexibilidad.

In [171]:
#Creamos una nueva columna con las nuevas categorías para "Hamstring_Flexibility"
df_csv['Hamstring_Flexibility_category'] = ""
df_csv.head(5)

#Sacamos los percentiles 33% y 66% de "Hamstring_Flexibility"
flex33 = int(df_csv['Hamstring_Flexibility'].quantile(0.33))
flex66 = int(df_csv['Hamstring_Flexibility'].quantile(0.66))
print(f'El percentil 33% es igual a {flex33} y el el percentil 66% es igual a {flex66}')

#Creamos las categorías para "Hamstring_Flexibility" y añadimos los nuevos valores en la columna "Hamstring_Flexibility_category"
for i in range (len(df_csv)):
    #Si el valor de cada fila en la columna "Hamstring_Flexibility" es menor que 76, el valor en cada fila en la columna "Hamstring_Flexibility_category" será 'Low'
    if df_csv.loc[df_csv.index[i],'Hamstring_Flexibility'] < flex33:
        df_csv.loc[df_csv.index[i],'Hamstring_Flexibility_category'] = 'Low'

#Si el valor de cada fila en la columna "Hamstring_Flexibility" es entre 76 y 82, el valor en cada fila en la columna "Hamstring_Flexibility_category" será 'Moderate'
    elif df_csv.loc[df_csv.index[i],'Hamstring_Flexibility'] >= flex33 and df_csv.loc[df_csv.index[i],'Hamstring_Flexibility'] <= flex66 :
        df_csv.loc[df_csv.index[i],'Hamstring_Flexibility_category'] = 'Moderate'

#Si el valor de cada fila en la columna "Hamstring_Flexibility" es mayor que 82, el valor en cada fila en la columna "Hamstring_Flexibility_category" será 'High'
    else:
        df_csv.loc[df_csv.index[i],'Hamstring_Flexibility_category'] = 'High'

df_csv[['Hamstring_Flexibility_category', 'Hamstring_Flexibility']].head(10)

El percentil 33% es igual a 76 y el el percentil 66% es igual a 82

   Hamstring_Flexibility_category  Hamstring_Flexibility
1                            High              82.541688
2                             Low              75.943631
3                             Low              73.878324
4                        Moderate              76.653043
5                        Moderate              80.927984
6                             Low              75.032030
7                        Moderate              76.947213
8                            High              89.584501
9                            High              82.244364
10                            Low              74.726306

Dividimos el nivel de estabilidad en tres niveles para analizar si un peor equilibrio está asociado a mayor riesgo de lesión. Como en las agrupaciones anteriores, al tener tantos valores distintos, agrupar a los jugadores en tres grupos nos simplifica el análisis posterior.

In [172]:
#Creamos una nueva columna con las nuevas categorías para "Balance_Test_Score"
df_csv['Balance_score'] = ""
df_csv.head(5)

#Sacamos los percentiles 33% y 66% de "Balance_Test_Score"
balance33 = int(df_csv['Balance_Test_Score'].quantile(0.33))
balance66 = int(df_csv['Balance_Test_Score'].quantile(0.66))
print(f'El percentil 33% es igual a {balance33} y el el percentil 66% es igual a {balance66}')

#Creamos las categorías para "Balance_Test_Score" y añadimos los nuevos valores en la columna "Balance_score"
for i in range (len(df_csv)):
    #Si el valor de cada fila en la columna "Balance_Test_Score" es menor que 81 , el valor en cada fila en la columna "Balance_score" será 'Poor'
    if df_csv.loc[df_csv.index[i],'Balance_Test_Score'] < balance33:
        df_csv.loc[df_csv.index[i],'Balance_score'] = 'Poor'

#Si el valor de cada fila en la columna "Balance_Test_Score" es entre 81 y 87, el valor en cada fila en la columna "Balance_score" será 'Moderate'
    elif df_csv.loc[df_csv.index[i],'Balance_Test_Score'] >= balance33 and df_csv.loc[df_csv.index[i],'Balance_Test_Score'] <= balance66 :
        df_csv.loc[df_csv.index[i],'Balance_score'] = 'Moderate'

#Si el valor de cada fila en la columna "Balance_Test_Score" es mayor que 87, el valor en cada fila en la columna "Balance_score" será 'High'
    else:
        df_csv.loc[df_csv.index[i],'Balance_score'] = 'High'

df_csv[['Balance_score', 'Balance_Test_Score']].head(20)

El percentil 33% es igual a 80 y el el percentil 66% es igual a 87

   Balance_score  Balance_Test_Score
1           High           87.294078
2       Moderate           83.440688
3           High           87.591894
4       Moderate           83.125161
5       Moderate           81.106339
6           Poor           76.787369
7           High           93.317382
8       Moderate           80.898575
9           High           89.077577
10          Poor           74.261622
11          Poor           74.462334
12          High           88.796646
13      Moderate           82.108525
14          Poor           79.782254
15          Poor           65.586739
16      Moderate           83.909148
17          Poor           78.083770
18      Moderate           84.687991
19      Moderate           84.697161
20          High           90.438687

### 
<div style="box-sizing:border-box;width:95%;display:flex;align-items:center;gap:1rem;padding:.9rem 1.75rem;border-left:2px solid rgba(196,168,130,0.35);font-family:'DM Sans',sans-serif;">
  <h3 style="font-family:'Playfair Display',serif;font-size:1.5rem;font-weight:400;color:#C4A882;margin:0;padding:0;border:none;line-height:1.2;">Dimensión 4: Rendimiento neuromuscular</h3>
</div>

Dividimos a los jugadores en dos grupos usando la mediana en base a su tiempo de reacción: reacción rápida y reacción lenta. El tiempo de reacción mide cuánto tarda el cuerpo en responder a un estímulo. A diferencia de otras variables, aquí menos es mejor.

In [173]:
#Creamos una nueva columna con las nuevas categorías para "Reaction_Time_ms"
df_csv['Reaction_time'] = ""
df_csv.head(5)

#sacamos el percentil 50% para categorizar si el reaction time es rápido o lento
reactionTime50 = int(df_csv['Reaction_Time_ms'].quantile(0.5))
print(f'El percentil 50 de reaction time es {reactionTime50} ms')

#Bucles for para categorizar la velocidad de reacción
for i in range (len(df_csv)):
    if df_csv.loc[df_csv.index[i], 'Reaction_Time_ms'] > reactionTime50:
         df_csv.loc[df_csv.index[i], 'Reaction_time'] = 'Slow'
    else:
         df_csv.loc[df_csv.index[i], 'Reaction_time'] = 'Fast'

df_csv[['Reaction_time', 'Reaction_Time_ms']].head(10)

El percentil 50 de reaction time es 249 ms

   Reaction_time  Reaction_Time_ms
1           Slow        250.579249
2           Slow        269.119918
3           Fast        226.376412
4           Fast        229.021042
5           Slow        265.801623
6           Slow        269.099907
7           Fast        226.966431
8           Fast        240.745054
9           Slow        259.628161
10          Slow        264.047546

Clasificamos en tres niveles para ver si hay relación con futuras lesiones. Esta mide la capacidad de cambiar de dirección de forma eficiente, atributo que es muy importante en el fútbol.

In [174]:
#Creamos una nueva columna con las nuevas categorías para "Agility_Score"
df_csv['Player_agility'] = ""
df_csv.head(5)

#Sacamos los percentiles 33% y 66% de "Balance_Test_Score"
agility33 = int(df_csv['Agility_Score'].quantile(0.33))
agility66 = int(df_csv['Agility_Score'].quantile(0.66))
print(f'El percentil 33% es igual a {agility33} y el el percentil 66% es igual a {agility66}')

#Creamos las categorías para "Agility_Score" y añadimos los nuevos valores en la columna "Player_agility"
for i in range (len(df_csv)):
    #Si el valor de cada fila en la columna "Agility_Score" es menor que 75 , el valor en cada fila en la columna "Player_agility" será 'Poor'
    if df_csv.loc[df_csv.index[i],'Agility_Score'] < agility33:
        df_csv.loc[df_csv.index[i],'Player_agility'] = 'Poor'

#Si el valor de cada fila en la columna "Agility_Score" es entre 75 y 82, el valor en cada fila en la columna "Player_agility" será 'Moderate'
    elif df_csv.loc[df_csv.index[i],'Agility_Score'] >= agility33 and df_csv.loc[df_csv.index[i],'Agility_Score'] <= agility66 :
        df_csv.loc[df_csv.index[i],'Player_agility'] = 'Moderate'

#Si el valor de cada fila en la columna "Agility_Score" es mayor que 82, el valor en cada fila en la columna "Player_agility" será 'High'
    else:
        df_csv.loc[df_csv.index[i],'Player_agility'] = 'High'

df_csv[['Player_agility', 'Agility_Score']].head(20)

El percentil 33% es igual a 74 y el el percentil 66% es igual a 82

   Player_agility  Agility_Score
1            High      94.418987
2            Poor      70.179176
3            High      83.473824
4            High      87.037256
5            High      86.418954
6            Poor      65.179995
7        Moderate      79.260417
8        Moderate      77.152290
9            High      90.396480
10       Moderate      80.813247
11       Moderate      74.857101
12       Moderate      79.846486
13           Poor      71.881054
14           High      83.618914
15       Moderate      76.818887
16       Moderate      78.751625
17           High      83.659735
18           Poor      69.153117
19       Moderate      76.845292
20           Poor      71.521769

Detectamos que la columna de velocidad de sprint tenía un nombre incorrecto que podía llevar a confusión. La corregimos y, además, creamos una nueva columna con la velocidad en km/h (unidad más familiar) para facilitar la interpretación de los resultados.

In [175]:
#Renombramos la columna "Sprint_Speed_10m_s" porque el valor no son 10 metros, es metro por segundo
df_csv.rename(columns={'Sprint_Speed_10m_s': 'Sprint_Speed_m_s'}, inplace=True)

#Creamos una nueva columna de km/h
df_csv['Sprint_Speed_km_h'] = 0.0
df_csv.head(5)

#Para convertir metros por segundo a km/h multiplicamos la columna "Sprint_Speed_m_s" por 3,6
df_csv['Sprint_Speed_km_h'] = round(df_csv['Sprint_Speed_m_s'] * 3.6, 1)

df_csv['Sprint_Speed_km_h']

1      20.9
2      20.6
3      22.4
4      19.4
5      22.9
       ...
795    20.8
796    20.1
797    19.7
798    23.6
799    21.2
Name: Sprint_Speed_km_h, Length: 799, dtype: float64

### 
<div style="box-sizing:border-box;width:95%;display:flex;align-items:center;gap:1rem;padding:.9rem 1.75rem;border-left:2px solid rgba(196,168,130,0.35);font-family:'DM Sans',sans-serif;">
  <h3 style="font-family:'Playfair Display',serif;font-size:1.5rem;font-weight:400;color:#C4A882;margin:0;padding:0;border:none;line-height:1.2;">Dimensión 5: Recuperación y estilo de vida</h3>
</div>

Clasificamos las horas de sueño en tres categorías (insuficiente, óptimo y excesivo) teniendo en cuenta la edad de cada jugador, ya que las horas recomendadas varían: los jugadores más jóvenes necesitan más sueño para recuperarse correctamente. Esta sensibilidad a la edad hace la categorización más precisa.

In [176]:
#Creamos una nueva columna de categorias del sueño
df_csv['Sleep_category'] = ""
df_csv.head(5)

#Creamos las categorías para "Sleep_Hours_Per_Night" y añadimos los nuevos valores en la columna "Sleep_category"
for i in range (len(df_csv)):
    #Si la edad del futbolista es entre 18 a 20 años lo recomnedable es dormir entre 8 y 10 horas al día. 
    #Si duerme duerme menos de 8 horas, la categoría de su sueño es "Insufficient"/ si duerme entre 8 y 10 horas es "Optimal" / si duerme más de 10 horas es "Excessive
    if df_csv.loc[df_csv.index[i],'Age'] >=18 and df_csv.loc[df_csv.index[i],'Age'] <= 20:
        if df_csv.loc[df_csv.index[i],'Sleep_Hours_Per_Night'] < 8:
            df_csv.loc[df_csv.index[i],'Sleep_category'] = 'Insufficient'
        elif df_csv.loc[df_csv.index[i],'Sleep_Hours_Per_Night'] >= 8 and df_csv.loc[df_csv.index[i],'Sleep_Hours_Per_Night'] <= 10:
            df_csv.loc[df_csv.index[i],'Sleep_category'] = 'Optimal'
        else:
            df_csv.loc[df_csv.index[i],'Sleep_category'] = 'Excessive'
    #Para los futbolistas mayores de 20 años lo recomnedable es dormir entre 7 y 9 horas al día. 
    #Si duerme menos de 7 horas, la categoría de su sueño es "Insufficient" / si duerme entre 7 y 9 horas es "Optimal" / si duerme más de 9 horas es "Excessive"
    else:
        if df_csv.loc[df_csv.index[i],'Sleep_Hours_Per_Night'] < 7:
            df_csv.loc[df_csv.index[i],'Sleep_category'] = 'Insufficient'
        elif df_csv.loc[df_csv.index[i],'Sleep_Hours_Per_Night'] >= 7 and df_csv.loc[df_csv.index[i],'Sleep_Hours_Per_Night'] <= 9:
            df_csv.loc[df_csv.index[i],'Sleep_category'] = 'Optimal'
        else:
            df_csv.loc[df_csv.index[i],'Sleep_category'] = 'Excessive'

df_csv[['Age', 'Sleep_Hours_Per_Night', 'Sleep_category']]

     Age  Sleep_Hours_Per_Night Sleep_category
1     18               8.983737        Optimal
2     22               7.229193        Optimal
3     20               7.681029   Insufficient
4     18               6.728091   Insufficient
5     23               8.538027        Optimal
..   ...                    ...            ...
795   22               7.631547        Optimal
796   21               7.676296        Optimal
797   24               6.798035   Insufficient
798   20               8.846476        Optimal
799   22               8.109630        Optimal

[799 rows x 3 columns]

Dividimos el nivel de estrés en tres grupos. El estrés elevado no es solo un problema psicológico: afecta la recuperación muscular, la calidad del sueño y la capacidad de concentración, factores que pueden influir directamente en el riesgo de lesión.

In [177]:
#Creamos una nueva columna con las nuevas categorías para "Stress_Level_Score"
df_csv['Stress_level'] = ""
df_csv.head(5)

#Sacamos los percentiles 33% y 66% de "Stress_Level_Score"
stress33 = int(df_csv['Stress_Level_Score'].quantile(0.33))
stress66 = int(df_csv['Stress_Level_Score'].quantile(0.66))
print(f'El percentil 33% es igual a {stress33} y el el percentil 66% es igual a {stress66}')

#Creamos las categorías para "Stress_Level_Score" y añadimos los nuevos valores en la columna "Stress_level"
for i in range (len(df_csv)):
    #Si el valor de cada fila en la columna "Stress_Level_Score" es menor que 49 , el valor en cada fila en la columna "Stress_level" será 'Low'
    if df_csv.loc[df_csv.index[i],'Stress_Level_Score'] < stress33:
        df_csv.loc[df_csv.index[i],'Stress_level'] = 'Low'

#Si el valor de cada fila en la columna "Stress_Level_Score" es entre 49 y 59, el valor en cada fila en la columna "Stress_level" será 'Medium'
    elif df_csv.loc[df_csv.index[i],'Stress_Level_Score'] >= stress33 and df_csv.loc[df_csv.index[i],'Stress_Level_Score'] <= stress66 :
        df_csv.loc[df_csv.index[i],'Stress_level'] = 'Medium'

#Si el valor de cada fila en la columna "Stress_Level_Score" es mayor que 59, el valor en cada fila en la columna "Stress_level" será 'High'
    else:
        df_csv.loc[df_csv.index[i],'Stress_level'] = 'High'

df_csv[['Stress_level', 'Stress_Level_Score']].head(20)

El percentil 33% es igual a 48 y el el percentil 66% es igual a 59

   Stress_level  Stress_Level_Score
1        Medium           49.368037
2           Low           43.132808
3        Medium           51.528529
4        Medium           52.379718
5           Low           39.929697
6          High           75.039112
7           Low           25.783371
8        Medium           52.581600
9        Medium           55.049722
10         High           77.728853
11         High           60.335046
12          Low           43.653777
13          Low           46.226068
14          Low           47.493992
15          Low           33.381323
16       Medium           55.377512
17       Medium           54.651794
18         High           62.317567
19       Medium           49.673913
20          Low           45.024989

La nutrición la clasificamos en cuatro niveles (mala, regular, buena y excelente) usando cuatro grupos de igual tamaño. Una mayor granularidad aquí nos permite ver si la mejora en la dieta tiene un efecto sobre la tasa de lesiones.

In [178]:
#Creamos una nueva columna con las nuevas categorías para "Nutrition_Quality_Score"
df_csv['Nutrition_quality'] = ""
df_csv.head(5)

#Sacamos los percentiles 33% y 66% de "Nutrition_Quality_Score"
nutrition25 = int(df_csv['Nutrition_Quality_Score'].quantile(0.25))
nutrition50 = int(df_csv['Nutrition_Quality_Score'].quantile(0.50))
nutrition75 = int(df_csv['Nutrition_Quality_Score'].quantile(0.75))
print(f'El percentil 25% es igual a {nutrition25}, el percentil 50% es igual a {nutrition50} y el percentil 75% es igual a {nutrition75}')

#Creamos las categorías para "Nutrition_Quality_Score" y añadimos los nuevos valores en la columna "Nutrition_quality"
for i in range (len(df_csv)):
    #Si el valor de cada fila en la columna "Stress_Level_Score" es menor que 67 , el valor en cada fila en la columna "Nutrition_quality" será 'Poor'
    if df_csv.loc[df_csv.index[i],'Nutrition_Quality_Score'] < nutrition25:
        df_csv.loc[df_csv.index[i],'Nutrition_quality'] = 'Poor'

#Si el valor de cada fila en la columna "Nutrition_Quality_Score" es entre 67 y 74, el valor en cada fila en la columna "Nutrition_quality" será 'Fair'
    elif df_csv.loc[df_csv.index[i],'Nutrition_Quality_Score'] >= nutrition25 and df_csv.loc[df_csv.index[i],'Nutrition_Quality_Score'] <= nutrition50 :
        df_csv.loc[df_csv.index[i],'Nutrition_quality'] = 'Fair'

#Si el valor de cada fila en la columna "Nutrition_Quality_Score" es entre 74 y 80, el valor en cada fila en la columna "Nutrition_quality" será 'Good'
    elif df_csv.loc[df_csv.index[i],'Nutrition_Quality_Score'] >= nutrition50 and df_csv.loc[df_csv.index[i],'Nutrition_Quality_Score'] <= nutrition75 :
        df_csv.loc[df_csv.index[i],'Nutrition_quality'] = 'Good'

#Si el valor de cada fila en la columna "Nutrition_Quality_Score" es mayor que 80, el valor en cada fila en la columna "Nutrition_quality" será 'Excellent'
    else:
        df_csv.loc[df_csv.index[i],'Nutrition_quality'] = 'Excellent'

df_csv[['Nutrition_quality', 'Nutrition_Quality_Score']].head(20)

El percentil 25% es igual a 67, el percentil 50% es igual a 74 y el percentil 75% es igual a 80

   Nutrition_quality  Nutrition_Quality_Score
1          Excellent                81.056677
2               Poor                64.877457
3          Excellent                89.824744
4               Fair                71.569197
5               Good                74.982476
6               Poor                65.790192
7          Excellent                89.782578
8               Good                78.587201
9          Excellent                83.947949
10              Poor                63.488951
11              Poor                59.963239
12              Good                75.520238
13         Excellent                88.220704
14              Good                77.838180
15              Poor                66.087769
16              Fair                69.060858
17              Poor                65.700243
18              Good                79.764972
19         Excellent                85.917363
20              Fair                68.823027

### 
<div style="box-sizing:border-box;width:95%;display:flex;align-items:center;gap:1rem;padding:.9rem 1.75rem;border-left:2px solid rgba(196,168,130,0.35);font-family:'DM Sans',sans-serif;">
  <h3 style="font-family:'Playfair Display',serif;font-size:1.5rem;font-weight:400;color:#C4A882;margin:0;padding:0;border:none;line-height:1.2;">Configuraciones finales</h3>
</div>

Con todas las categorías creadas, hacemos un último repaso de todas las columnas y eliminamos las que ya no son necesarias, por ejemplo, aquellas que han sido sustituidas por versiones mejoradas o más legibles. Así, el dataset queda limpio, organizado y listo para las visualizaciones.

In [179]:
# Sacamos el nombre y total de columnas y eliminamos las que no nos interesan
df_csv.info()
df_csv.drop(columns=['Sprint_Speed_m_s', 'Training_Hours_Per_Week'])

<class 'pandas.DataFrame'>
RangeIndex: 799 entries, 1 to 799
Data columns (total 33 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Age                             799 non-null    int64
 1   Height_cm                       799 non-null    float64
 2   Weight_kg                       799 non-null    int64
 3   Position                        799 non-null    str
 4   Training_Hours_Per_Week         799 non-null    float64
 5   Matches_Played_Past_Season      799 non-null    int64
 6   Previous_Injury_Count           799 non-null    int64
 7   Knee_Strength_Score             799 non-null    float64
 8   Hamstring_Flexibility           799 non-null    float64
 9   Reaction_Time_ms                799 non-null    float64
 10  Balance_Test_Score              799 non-null    float64
 11  Sprint_Speed_m_s                799 non-null    float64
 12  Agility_Score                   799 non-null    float64
 13  Sleep_Hours_Per_Night           799 non-null    float64
 14  Stress_Level_Score              799 non-null    float64
 15  Nutrition_Quality_Score         799 non-null    float64
 16  Warmup_Routine_Adherence        799 non-null    bool
 17  Injury_Current_Season           799 non-null    bool
 18  BMI                             799 non-null    float64
 19  Height_category                 799 non-null    str
 20  Weight_category                 799 non-null    str
 21  Body_Mass_Index                 799 non-null    str
 22  Training_Hours_Per_Day          799 non-null    float64
 23  Matches_range_past_season       799 non-null    str
 24  Knee_Strength                   799 non-null    str
 25  Hamstring_Flexibility_category  799 non-null    str
 26  Balance_score                   799 non-null    str
 27  Reaction_time                   799 non-null    str
 28  Player_agility                  799 non-null    str
 29  Sprint_Speed_km_h               799 non-null    float64
 30  Sleep_category                  799 non-null    str
 31  Stress_level                    799 non-null    str
 32  Nutrition_quality               799 non-null    str
dtypes: bool(2), float64(14), int64(4), str(13)
memory usage: 195.2 KB

,Age,Height_cm,Weight_kg,Position,Matches_Played_Past_Season,Previous_Injury_Count,Knee_Strength_Score,Hamstring_Flexibility,Reaction_Time_ms,Balance_Test_Score,...,Matches_range_past_season,Knee_Strength,Hamstring_Flexibility_category,Balance_score,Reaction_time,Player_agility,Sprint_Speed_km_h,Sleep_category,Stress_level,Nutrition_quality
1,18,170.0,67,Midfielder,37,2,72.634442,82.541688,250.579249,87.294078,...,More than 30,Medium,High,High,Slow,High,20.9,Optimal,Medium,Excellent
2,22,186.0,75,Forward,12,2,77.064490,75.943631,269.119918,83.440688,...,10 - 20,Strong,Low,Moderate,Slow,Poor,20.6,Optimal,Low,Poor
3,20,172.0,62,Defender,11,1,82.810232,73.878324,226.376412,87.591894,...,10 - 20,Strong,Low,High,Fast,High,22.4,Insufficient,Medium,Excellent
4,18,172.0,94,Midfielder,10,2,76.772859,76.653043,229.021042,83.125161,...,10 - 20,Medium,Moderate,Moderate,Fast,High,19.4,Insufficient,Medium,Fair
5,23,189.0,89,Goalkeeper,31,2,78.450720,80.927984,265.801623,81.106339,...,More than 30,Strong,Moderate,Moderate,Slow,High,22.9,Optimal,Low,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,22,182.0,63,Goalkeeper,33,1,72.678400,84.620355,240.117111,74.372627,...,More than 30,Medium,High,Poor,Fast,Moderate,20.8,Optimal,High,Good
796,21,181.0,66,Defender,11,2,67.290644,70.726745,260.341118,85.392132,...,10 - 20,Weak,Low,Moderate,Slow,Moderate,20.1,Optimal,High,Good
797,24,182.0,75,Goalkeeper,17,3,81.164089,83.486771,264.192657,84.031046,...,10 - 20,Strong,High,Moderate,Slow,Poor,19.7,Insufficient,High,Good
798,20,188.0,86,Goalkeeper,35,1,71.184901,85.585050,204.446478,84.417342,...,More than 30,Weak,High,Moderate,Fast,Poor,23.6,Optimal,Medium,Fair
799,22,186.0,73,Midfielder,15,1,59.709613,72.966692,255.770337,84.186100,...,10 - 20,Weak,Low,Moderate,Slow,Poor,21.2,Optimal,High,Fair

##
<style>
@import url('https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400&family=DM+Sans:opsz,wght@9..40,300;9..40,400;9..40,500&display=swap');
</style>

<div style="box-sizing:border-box;width:95%;background:#2C2825;border-radius:10px;position:relative;overflow:hidden;font-family:'DM Sans',sans-serif;display:flex;align-items:center;gap:1.5rem;padding:1.6rem 2.5rem;">
  <div style="position:absolute;inset:0;background:radial-gradient(ellipse 40% 120% at 100% 50%,rgba(196,168,130,0.1) 0%,transparent 65%);pointer-events:none;"></div>
  <span style="font-family:'Playfair Display',serif;font-size:3rem;font-weight:400;color:rgba(196,168,130,0.2);line-height:1;flex-shrink:0;position:relative;z-index:1;">05</span>
  <div style="width:1px;height:36px;background:rgba(196,168,130,0.2);flex-shrink:0;position:relative;z-index:1;"></div>
  <div style="position:relative;z-index:1;">
    <p style="font-size:10px;letter-spacing:.22em;text-transform:uppercase;color:#C4A882;margin:0 0 .25rem;font-weight:500;">Paso 5</p>
    <h2 style="font-family:'Playfair Display',serif;font-size:1.55rem;font-weight:400;color:#FAF7F2;margin:0;padding:0;border:none;line-height:1.2;">Visualizaciones</h2>
  </div>
</div>

*Llegamos a la fase donde todo el trabajo previo cobra sentido. Cada gráfico responde a una pregunta concreta: ¿qué factores están relacionados con el riesgo de lesión? El análisis sigue las mismas cinco dimensiones que usamos para categorizar los datos, lo que garantiza coherencia de principio a fin.*

### 
<div style="box-sizing:border-box;width:95%;display:flex;align-items:center;gap:1rem;padding:.9rem 1.75rem;border-left:2px solid rgba(196,168,130,0.35);font-family:'DM Sans',sans-serif;">
  <h3 style="font-family:'Playfair Display',serif;font-size:1.5rem;font-weight:400;color:#C4A882;margin:0;padding:0;border:none;line-height:1.2;">Instalamos librerias matplotlib, pyplot y nbformat</h3>
</div>

Cargamos las librerías necesarias para crear los gráficos. Usaremos principalmente Plotly, que genera visualizaciones interactivas como pasar el cursor para ver valores exactos y explorar los datos de forma dinámica.

In [180]:
%pip install matplotlib plotly nbformat
import matplotlib.pyplot as plt
import plotly.express as px
from plotly.subplots import make_subplots

Requirement already satisfied: matplotlib in ./.venv/lib/python3.13/site-packages (3.10.8)
Requirement already satisfied: plotly in ./.venv/lib/python3.13/site-packages (6.6.0)
Requirement already satisfied: nbformat in ./.venv/lib/python3.13/site-packages (5.10.4)
Requirement already satisfied: contourpy>=1.0.1 in ./.venv/lib/python3.13/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in ./.venv/lib/python3.13/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in ./.venv/lib/python3.13/site-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in ./.venv/lib/python3.13/site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.23 in ./.venv/lib/python3.13/site-packages (from matplotlib) (2.4.3)
Requirement already satisfied: packaging>=20.0 in ./.venv/lib/python3.13/site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in ./.venv/lib/python3.13/site-packages (from matplotlib) (12.1.1)
Requirement already satisfied: pyparsing>=3 in ./.venv/lib/python3.13/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in ./.venv/lib/python3.13/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: narwhals>=1.15.1 in ./.venv/lib/python3.13/site-packages (from plotly) (2.18.1)
Requirement already satisfied: fastjsonschema>=2.15 in ./.venv/lib/python3.13/site-packages (from nbformat) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in ./.venv/lib/python3.13/site-packages (from nbformat) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in ./.venv/lib/python3.13/site-packages (from nbformat) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in ./.venv/lib/python3.13/site-packages (from nbformat) (5.14.3)
Requirement already satisfied: attrs>=22.2.0 in ./.venv/lib/python3.13/site-packages (from jsonschema>=2.6->nbformat) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in ./.venv/lib/python3.13/site-packages (from jsonschema>=2.6->nbformat) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in ./.venv/lib/python3.13/site-packages (from jsonschema>=2.6->nbformat) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in ./.venv/lib/python3.13/site-packages (from jsonschema>=2.6->nbformat) (0.30.0)
Requirement already satisfied: platformdirs>=2.5 in ./.venv/lib/python3.13/site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.9.4)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.13/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

### 
<div style="box-sizing:border-box;width:95%;display:flex;align-items:center;gap:1rem;padding:.9rem 1.75rem;border-left:2px solid rgba(196,168,130,0.35);font-family:'DM Sans',sans-serif;">
  <h3 style="font-family:'Playfair Display',serif;font-size:1.5rem;font-weight:400;color:#C4A882;margin:0;padding:0;border:none;line-height:1.2;">Analizamos el número de jugadores lesionados esta temporada en base al número de lesiones previas que tuvo cada jugador</h3>
</div>

Calculamos el número total de jugadores lesionados y no lesionados durante la temporada actual. Este dato es nuestra referencia base: todo lo que analicemos después se comparará con esta proporción general.

In [181]:
print(df_csv['Injury_Current_Season'].value_counts())

Injury_Current_Season
True     400
False    399
Name: count, dtype: int64

Este gráfico circular muestra de forma inmediata qué proporción de la plantilla se lesionó. De cada 100 jugadores, aproximadamente cuántos sufrieron una lesión durante la temporada.

In [243]:
# Calculamos el total de lesionados y no lesionados en esta temporada.
injured = (df_csv['Injury_Current_Season'] == True).sum()
notInjured = (df_csv['Injury_Current_Season'] == False).sum()

# Creamos un DataFrame (Plotly trabaja mejor así)
df_pie = pd.DataFrame({
    'Estado': ['Injured', 'Not Injured'],
    'Count': [injured, notInjured]
})

# Gráfico circular
fig = px.pie(
    df_pie,
    names='Estado',
    values='Count',
    title='Distribución de lesiones durante la temporada actual',
    color='Estado',
    color_discrete_map={
        'Injured': '#E53935',
        'Not Injured': '#43A047'
    }
)

# Mostrar porcentajes y estilo
fig.update_traces(
    textinfo='percent+label',
    pull=[0.05, 0],  # equivalente a explode
    textfont_size=12
)

fig.update_layout(title_x=0.5, template='plotly_white', width=700)

fig.show()

# Mostramos también los valores absolutos debajo del gráfico.
print(f"\nLa proporción de jugadores lesionados y no lesionados está prácticamente equilibrada: {injured} futbolistas se lesionaron y {notInjured} futbolistas no se lesionaron.")

La proporción de jugadores lesionados y no lesionados está prácticamente equilibrada: 400 futbolistas se lesionaron y 399 futbolistas no se lesionaron.

Exploramos el historial de lesiones de la plantilla: cuántos jugadores llegan a esta temporada sin ninguna lesión previa, cuántos con una o dos, y cuántos con un historial más largo. Esto nos da el perfil histórico del grupo antes de analizar el riesgo.

In [183]:
print(df_csv['Previous_Injury_Count'].value_counts())

Previous_Injury_Count
1    258
2    187
0    185
3    106
4     43
5     17
7      1
6      1
8      1
Name: count, dtype: int64

Este gráfico de barras muestra cuántos jugadores hay en cada nivel de historial de lesiones. Podemos ver si la mayoría llega sin antecedentes o si hay una parte significativa de la plantilla con un historial acumulado importante.

In [241]:
# Mostramos qué porcentaje de jugadores se han lesionado esta temporada en base al número de lesiones previas
previousInjuryCount = df_csv['Previous_Injury_Count'].value_counts().reset_index()
previousInjuryCount.columns = ['Previous_Injury_Count', 'Count']

# px.bar() crea un gráfico de barras interactivo.
fig = px.bar(
    previousInjuryCount,
    x='Previous_Injury_Count',
    y='Count',
    text='Count',
    title='Distribución del número de lesiones previas',
    labels={
        'Previous_Injury_Count': 'Número de lesiones previas',
        'Count': 'Nº jugadores'
    },
    color_discrete_sequence=["#43A047"]
)

# fig.update_traces() pinta los porcentajes encima de las barras.
# texttemplate='%{text:,.0f}' formatea el texto con separador de miles.
# textposition='outside' coloca el texto fuera de la barra.

#fig.update_layout(template='plotly_white') pone el fondo de color blanco
#fig.update_yaxes(range=[0, 110]) pone la altura del eje Y
fig.update_layout(template='plotly_white', title_x=0.5)
fig.update_yaxes(range=[0, 260])

fig.show()
print(f'La mayoría de los jugadores tiene pocas lesiones previas (0–2), y los casos con muchas lesiones son muy poco frecuentes.')

La mayoría de los jugadores tiene pocas lesiones previas (0–2), y los casos con muchas lesiones son muy poco frecuentes.

Este mapa de calor nos muestra la distribución de futbolistas según su número de lesiones previas y si han sufrido una lesión en la temporada actual, permitiendo explorar la posible relación entre ambos factores.

In [244]:
# Creamos una tabla cruzada con el numero de lesionados y no lesionados dependiendo del numero de lesiones previas: 
# index='Injury_Current_Season' define las filas (True o False), columns='Previous_Injury_Count' define las columnas (de 0 a 8), aggfunc='size' muestra el numero de jugadores para cada combinación.
heatmap_data = df_csv.pivot_table(
    index='Injury_Current_Season',
    columns='Previous_Injury_Count',
    aggfunc='size'
)

# px.imshow() crea un mapa de calor interactivo.
# text_auto=True      → muestra los valores numéricos dentro de cada celda
# color_continuous_scale → paleta de colores
#   'YlOrRd' = Amarillo → Naranja → Rojo (bajo → alto)
#   Otras opciones: 'Blues', 'Viridis', 'Plasma', 'RdBu'
# aspect='auto'       → ajusta el aspecto para que se vea bien
fig = px.imshow(
    heatmap_data,
    text_auto=True,
    color_continuous_scale='YlOrRd',
    title='Relación entre lesiones previas y lesiones en la temporada actual ',
    labels={'x': 'Número de lesiones previas', 'y': 'Lesionado esta temporada', 'color': 'Futbolistas'},
    aspect='auto'
)

# Renombramos las etiquetas del eje Y con los valores 'True' y 'False' (antes eran 'true' y 'false').
fig.update_yaxes(
    tickmode='array',
    tickvals=list(range(0, 2)),
    ticktext=['False ', 'True ']
)

fig.update_layout(template='plotly_white', title_x=0.5)
fig.show()

print(f'Podemos observar que a mayor número de lesiones previas, mayor probabilidad de lesionarse en la temporada actual.')

Podemos observar que a mayor número de lesiones previas, mayor probabilidad de lesionarse en la temporada actual.

Comprobamos que los números que muestra el gráfico son correctos contrastándolos con los datos originales. Es un paso de validación interna que garantiza la fiabilidad de la visualización.

In [186]:
#Imprimimos las el número de cada combinación para comprobar que los valores del heatmap sean correctos
for i in range (0, 9):
    print(f'Para {i} lesiones previas, estos son los resultados: {df_csv[df_csv['Previous_Injury_Count'] == i]['Injury_Current_Season'].value_counts()}')

Para 0 lesiones previas, estos son los resultados: Injury_Current_Season
False    138
True      47
Name: count, dtype: int64
Para 1 lesiones previas, estos son los resultados: Injury_Current_Season
False    147
True     111
Name: count, dtype: int64
Para 2 lesiones previas, estos son los resultados: Injury_Current_Season
True     106
False     81
Name: count, dtype: int64
Para 3 lesiones previas, estos son los resultados: Injury_Current_Season
True     79
False    27
Name: count, dtype: int64
Para 4 lesiones previas, estos son los resultados: Injury_Current_Season
True     39
False     4
Name: count, dtype: int64
Para 5 lesiones previas, estos son los resultados: Injury_Current_Season
True     15
False     2
Name: count, dtype: int64
Para 6 lesiones previas, estos son los resultados: Injury_Current_Season
True    1
Name: count, dtype: int64
Para 7 lesiones previas, estos son los resultados: Injury_Current_Season
True    1
Name: count, dtype: int64
Para 8 lesiones previas, estos son los resultados: Injury_Current_Season
True    1
Name: count, dtype: int64

Este es el gráfico clave de este bloque. No miramos cuántos jugadores se lesionaron en total, sino qué porcentaje de cada grupo lo hizo. Así podemos comparar en igualdad de condiciones: si la tendencia sube con el historial, el pasado predice el riesgo futuro.

In [245]:
# Mostramos qué porcentaje de jugadores se han lesionado esta temporada en base al número de lesiones previas
percentageInjury = df_csv.groupby('Previous_Injury_Count')['Injury_Current_Season'].mean() * 100

percentageInjury = percentageInjury.reset_index()
percentageInjury.columns = ['Previous_Injury_Count', 'Injury_Percentage']

# px.bar() crea un gráfico de barras interactivo.
fig = px.bar(
    percentageInjury,
    x='Previous_Injury_Count',
    y='Injury_Percentage',
    title='Porcentaje de lesión según lesiones previas',
    labels={
        'Previous_Injury_Count': 'Número de lesiones previas',
        'Injury_Percentage': 'Probabilidad de lesión (%)'
    },
    color='Injury_Percentage',
    color_continuous_scale='Blues',
    range_color=[0, percentageInjury['Injury_Percentage'].max()]
)

# fig.update_traces() pinta los porcentajes encima de las barras.
# texttemplate='%{text:,.0f}' formatea el texto con separador de miles.
# textposition='outside' coloca el texto fuera de la barra.
fig.update_traces(texttemplate='%{y:.1f}%', textposition='inside')

#fig.update_layout(template='plotly_white') pone el fondo de color blanco
#fig.update_yaxes(range=[0, 110]) pone la altura del eje Y
fig.update_layout(template='plotly_white', title_x=0.5)
fig.update_yaxes(range=[0, 110])

fig.show()
print(f'La probabilidad de lesionarse aumenta claramente a medida que crece el número de lesiones previas.')

La probabilidad de lesionarse aumenta claramente a medida que crece el número de lesiones previas.

### 
<div style="box-sizing:border-box;width:95%;display:flex;align-items:center;gap:1rem;padding:.9rem 1.75rem;border-left:2px solid rgba(196,168,130,0.35);font-family:'DM Sans',sans-serif;">
  <h3 style="font-family:'Playfair Display',serif;font-size:1.5rem;font-weight:400;color:#C4A882;margin:0;padding:0;border:none;line-height:1.2;">Analizamos el número de jugadores lesionados esta temporada en base a la posición en el campo cada jugador</h3>
</div>

Analizamos si hay posiciones en el campo más expuestas a las lesiones que otras. Las barras apiladas nos permiten ver a la vez el número total de jugadores por posición y la proporción de lesionados dentro de cada una.

In [246]:
# Sacamos por posición tanto el número de jugadores que se han lesionado durante esta temporada como los que no.
datos_stacked = df_csv.groupby(['Position', 'Injury_Current_Season']).size().reset_index(name='Count')

# px.bar() con barmode='stack' crea barras APILADAS.
# Diferencia con barras agrupadas:
#   - Agrupadas (barmode='group'): barras lado a lado → compara valores individuales
#   - Apiladas (barmode='stack'): barras una encima de otra → compara totales y composición
# color='Injury_Current_Season'      → cada valor de la columna Injury_Current_Season tiene un color diferente
# color_discrete_map={...} → asignamos colores específicos a cada valor de la columna Injury_Current_Season
fig = px.bar(
    datos_stacked,
    x='Position',
    y='Count',
    color='Injury_Current_Season',
    text='Count',
    barmode='stack',
    title='Número de lesionados por posición',
    labels={'Position': 'Posición', 'Injury_Current_Season': 'Lesionado', 'Count': 'Nº jugadores'},
    color_discrete_map={False: '#E53935', True: '#FB8C00'}
)

# template='plotly_white' aplica un tema visual limpio con fondo blanco.
# Otros templates disponibles: 'plotly', 'plotly_dark', 'seaborn', 'simple_white'
fig.update_layout(template='plotly_white', title_x=0.5)

# fig.show() renderiza el gráfico interactivo.
# Pasa el ratón por cada sección de la barra para ver los valores.
fig.show()
print(f'No existen grandes diferencias en el número de lesionados entre posiciones, aunque los centrocampistas y delanteros presentan ligeramente más casos.')

No existen grandes diferencias en el número de lesionados entre posiciones, aunque los centrocampistas y delanteros presentan ligeramente más casos.

### 
<div style="box-sizing:border-box;width:95%;display:flex;align-items:center;gap:1rem;padding:.9rem 1.75rem;border-left:2px solid rgba(196,168,130,0.35);font-family:'DM Sans',sans-serif;">
  <h3 style="font-family:'Playfair Display',serif;font-size:1.5rem;font-weight:400;color:#C4A882;margin:0;padding:0;border:none;line-height:1.2;">Dimensión 1: Demografía y características físicas</h3>
</div>

Este panel de cuatro gráficos nos da una visión de conjunto de cómo las características físicas se relacionan con las lesiones. Analizamos si hay edades con más lesiones, si el índice de masa corporal influye, y si el peso o la altura marcan alguna diferencia.

In [252]:
# Creamos el numero de subplots
fig = make_subplots(
    rows=2, cols=2,
    specs=[[{"type": "xy"}, {"type": "xy"}],
           [{"type": "xy"}, {"type": "xy"}]],
    subplot_titles=(
        "Porcentaje de lesiones por edad",
        "Distribución lesiones por BMI",
        "Porcentaje de lesiones por categoría de peso",
        "Porcentaje de lesiones por categoría de altura"
    )
)

# Gráfico Age
lesiones_age = (
    df_csv.groupby('Age', as_index=False)
    .agg(
        lesionados=('Injury_Current_Season', 'sum'),
        total=('Injury_Current_Season', 'count')
    )
)

lesiones_age['Injury_Current_Season'] = (
    lesiones_age['lesionados'] / lesiones_age['total'] * 100
)

fig_age = px.line(
    lesiones_age,
    x='Age',
    y='Injury_Current_Season',
    markers=True,
    text='Injury_Current_Season'
)

for trace in fig_age.data:
    trace.update(
        line=dict(width=3, color='#1E88E5'),
        marker=dict(size=9),
        textposition='top center',
        texttemplate='%{text:.1f}%',
        hovertemplate='Edad: %{x}<br>% Lesionados: %{y:.1f}%<extra></extra>'
    )
    fig.add_trace(trace, row=1, col=1)

fig.update_yaxes(
    title_text='% de lesionados esta temporada',
    ticksuffix='%',
    range=[40, 60],
    row=1,
    col=1
)

# Gráfico BMI
lesiones_bmi = (
    df_csv.groupby('Body_Mass_Index', as_index=False)
    .agg(
        lesionados=('Injury_Current_Season', 'sum'),
        total=('Injury_Current_Season', 'count')
    )
)

lesiones_bmi['Injury_Current_Season'] = (
    lesiones_bmi['lesionados'] / lesiones_bmi['total'] * 100
)

orden = ['Underweight', 'Normal weight', 'Overweight', 'Obesity']
lesiones_bmi['Body_Mass_Index'] = pd.Categorical(
    lesiones_bmi['Body_Mass_Index'],
    categories=orden,
    ordered=True
)
lesiones_bmi = lesiones_bmi.sort_values('Body_Mass_Index')

# Line chart
fig_bmi = px.line(
    lesiones_bmi,
    x='Body_Mass_Index',
    y='Injury_Current_Season',
    markers=True,
    text='Injury_Current_Season'
)

for trace in fig_bmi.data:
    trace.update(
        line=dict(width=3, color='#43A047'),
        marker=dict(size=9),
        textposition='top center',
        texttemplate='%{text:.1f}%',
        hovertemplate='BMI: %{x}<br>% Lesionados: %{y:.1f}%<extra></extra>'
    )
    fig.add_trace(trace, row=1, col=2)  # ajusta col si hace falta

fig.update_yaxes(
    title_text='% de lesionados esta temporada',
    ticksuffix='%',
    range=[0, 100],
    row=1,
    col=2
)

# Gráfico Weight
lesiones_weight = (
    df_csv.groupby('Weight_category', as_index=False)
    .agg(
        lesionados=('Injury_Current_Season', 'sum'),
        total=('Injury_Current_Season', 'count')
    )
)

lesiones_weight['Injury_Current_Season'] = (
    lesiones_weight['lesionados'] / lesiones_weight['total'] * 100
)

lesiones_weight = lesiones_weight.sort_values('Injury_Current_Season', ascending=False)

fig_weight = px.bar(
    lesiones_weight,
    x='Weight_category',
    y='Injury_Current_Season',
    text=lesiones_weight['Injury_Current_Season'].round(1)
)

for trace in fig_weight.data:
    trace.update(
        marker_color='#43A047',
        width=0.5,
        textposition='outside',
        texttemplate='%{text:.1f}%',
        hovertemplate='Peso: %{x}<br>% Lesionados: %{y:.1f}%<extra></extra>'
    )
    fig.add_trace(trace, row=2, col=1)

fig.update_yaxes(range=[0, 100], ticksuffix='%', row=2, col=1)

# Gráfico Height
lesiones_height = (
    df_csv.groupby('Height_category', as_index=False)
    .agg(
        lesionados=('Injury_Current_Season', 'sum'),
        total=('Injury_Current_Season', 'count')
    )
)

lesiones_height['Injury_Current_Season'] = (
    lesiones_height['lesionados'] / lesiones_height['total'] * 100
)

lesiones_height = lesiones_height.sort_values('Injury_Current_Season', ascending=False)

fig_height = px.bar(
    lesiones_height,
    x='Height_category',
    y='Injury_Current_Season',
    text=lesiones_height['Injury_Current_Season'].round(1)
)

for trace in fig_height.data:
    trace.update(
        marker_color='#CE7ADB',
        width=0.5,
        textposition='outside',
        texttemplate='%{text:.1f}%',
        hovertemplate='Altura: %{x}<br>% Lesionados: %{y:.1f}%<extra></extra>'
    )
    fig.add_trace(trace, row=2, col=2)

fig.update_yaxes(range=[0, 100], ticksuffix='%', row=2, col=2)

# Layout general
fig.update_layout(
    title={
        'text': 'Panel de Análisis — Demografía y características físicas',
        'x': 0.5,
        'xanchor': 'center'
    },
    template='plotly_white',
    height=850,
    width=1200,
    showlegend=False,
    margin=dict(t=80, l=100, r=50, b=50)
)

# Ejes
fig.update_xaxes(title_text='Edad', row=1, col=1)
fig.update_yaxes(title_text='Porcentaje de lesiones esta temporada', row=1, col=1)

fig.update_xaxes(title_text='Índice de Masa Corporal', row=1, col=2)
fig.update_yaxes(title_text='Porcentaje de lesiones esta temporada', row=1, col=1)

fig.update_xaxes(title_text='Peso', row=2, col=1)
fig.update_yaxes(title_text='Porcentaje de lesiones esta temporada', row=2, col=1)

fig.update_xaxes(title_text='Altura', row=2, col=2)
fig.update_yaxes(title_text='Porcentaje de lesiones esta temporada', row=2, col=2)

fig.show()

print(f'Las variables físicas (edad, IMC, peso y altura) muestran diferencias leves en el porcentaje de lesiones, pero ninguna destaca como un factor claramente determinante.')
print(f'Los futbolistas con mayor probabilidad de lesión tienen 21 años (54.55%), miden < 174 cm (54.15%), y pesan entre 69 - 77 kg (51.06%)')

Las variables físicas (edad, IMC, peso y altura) muestran diferencias leves en el porcentaje de lesiones, pero ninguna destaca como un factor claramente determinante.
Los futbolistas con mayor probabilidad de lesión tienen 21 años (54.55%), miden < 174 cm (54.15%), y pesan entre 69 - 77 kg (51.06%)

In [247]:
df_csv[df_csv['Body_Mass_Index'] == 'Obesity'].shape[0]

32

### 
<div style="box-sizing:border-box;width:95%;display:flex;align-items:center;gap:1rem;padding:.9rem 1.75rem;border-left:2px solid rgba(196,168,130,0.35);font-family:'DM Sans',sans-serif;">
  <h3 style="font-family:'Playfair Display',serif;font-size:1.5rem;font-weight:400;color:#C4A882;margin:0;padding:0;border:none;line-height:1.2;">Dimensión 2: Carga de entrenamiento y competición</h3>
</div>

¿Entrenar más horas aumenta el riesgo de lesión? Este gráfico responde a esa pregunta mostrando el porcentaje de lesionados para cada nivel de carga de entrenamiento diaria. Si la barra más alta coincide con la mayor carga, tenemos una señal clara de sobrecarga como factor de riesgo.

In [255]:
# Mostramos qué porcentaje de jugadores se han lesionado esta temporada en base al número de lesiones previas
trainingHoursDayInjury = df_csv.groupby('Training_Hours_Per_Day')['Injury_Current_Season'].mean()*100

trainingHoursDayInjury = trainingHoursDayInjury.reset_index()
trainingHoursDayInjury.columns = ['Training_Hours_Per_Day', 'Injured_Players']

# px.bar() crea un gráfico de barras interactivo.
fig = px.bar(
    trainingHoursDayInjury,
    x='Training_Hours_Per_Day',
    y='Injured_Players',
    title='Porcentaje de jugadores lesionados según su carga de entrenamiento diaria',
    labels={
        'Training_Hours_Per_Day': 'Horas diarias entrenadas',
        'Injured_Players': '% Futbolistas lesionados'
    },
    color='Injured_Players',
    color_continuous_scale='Oranges'
)

# fig.update_traces() pinta los porcentajes encima de las barras.
# texttemplate='%{text:,.0f}' formatea el texto con separador de miles.
# textposition='outside' coloca el texto fuera de la barra.
fig.update_traces(texttemplate='%{y:.1f}%', textposition='outside')

#fig.update_layout(template='plotly_white') pone el fondo de color blanco
#fig.update_yaxes(range=[0, 110]) pone la altura del eje Y
fig.update_layout(template='plotly_white', title_x=0.5)
fig.update_yaxes(range=[0, 110])

fig.show()
print(f'Observamos que a mayor carga de entrenamiento diaria, mayor porcentaje de jugadores lesionados, especialmente a partir de las 2.5–3 horas de entrenamiento diario.')

Observamos que a mayor carga de entrenamiento diaria, mayor porcentaje de jugadores lesionados, especialmente a partir de las 2.5–3 horas de entrenamiento diario.

Los partidos jugados la temporada anterior son una medida de la fatiga acumulada con la que el jugador llega a la temporada actual. Este gráfico de línea muestra si hay un umbral de partidos a partir del cual el riesgo de lesión aumenta de forma notable.

In [238]:
# Mostramos el porcentaje de judagores lesionados en función a la carga de partidos de la temporada pasada
matchesPlayedInjury = round(df_csv.groupby('Matches_Played_Past_Season')['Injury_Current_Season'].mean()*100, 2)

matchesPlayedInjury = matchesPlayedInjury.reset_index()
matchesPlayedInjury.columns = ['Matches_Played_Past_Season', 'Injured_Players']

fig = px.line(
    matchesPlayedInjury,
    x='Matches_Played_Past_Season',
    y='Injured_Players',
    markers=True,
    text='Injured_Players',
    labels={
        'Matches_Played_Past_Season': 'Partidos jugados temporada pasada',
        'Injured_Players': '% Futbolistas lesionados'
    }
)

for trace in fig.data:
    trace.update(
        line=dict(width=3, color='#1E88E5'),
        marker=dict(size=9),
        textposition='top center',
        hovertemplate='Número de partidos %{x}<br>% Jugadores lesionados: %{y}<extra></extra>'
    )

# Layout general
fig.update_layout(
    title={
        'text': 'Porcentaje de jugadores lesionados según el número de partidos jugados la temporada pasada',
        'x': 0.5,
        'xanchor': 'center'
    },
    template='plotly_white',
    height=500,
    width=1000,
    showlegend=False,
    margin=dict(t=80, l=50, r=50, b=50)
)


fig.show()
print(f'No se observa una relación clara o lineal entre el número de partidos jugados y el porcentaje de jugadores lesionados.')

No se observa una relación clara o lineal entre el número de partidos jugados y el porcentaje de jugadores lesionados.

### 
<div style="box-sizing:border-box;width:95%;display:flex;align-items:center;gap:1rem;padding:.9rem 1.75rem;border-left:2px solid rgba(196,168,130,0.35);font-family:'DM Sans',sans-serif;">
  <h3 style="font-family:'Playfair Display',serif;font-size:1.5rem;font-weight:400;color:#C4A882;margin:0;padding:0;border:none;line-height:1.2;">Dimensión 3: Condición física / biomecánica</h3>
</div>

Antes de visualizar, calculamos numéricamente cuánto está relacionada cada variable biomecánica con las lesiones. Esto nos ayuda a entender qué indicadores tienen más peso y merecen más atención en el análisis.

In [193]:
df_csv[['Knee_Strength_Score', 'Hamstring_Flexibility', 'Balance_Test_Score', 'Injury_Current_Season']].corr()

,Knee_Strength_Score,Hamstring_Flexibility,Balance_Test_Score,Injury_Current_Season
Knee_Strength_Score,1.000000,0.181545,0.232299,-0.454401
Hamstring_Flexibility,0.181545,1.000000,0.207093,-0.450607
Balance_Test_Score,0.232299,0.207093,1.000000,-0.494140
Injury_Current_Season,-0.454401,-0.450607,-0.494140,1.000000

¿Los jugadores con menos fuerza en la rodilla se lesionan más? Este gráfico compara la tasa de lesión entre los tres grupos de fuerza. Si la diferencia es clara, el trabajo de fortalecimiento de rodilla se convierte en una herramienta de prevención directa.

In [256]:
# Mostramos qué porcentaje de jugadores se han lesionado esta temporada en base a su nivel de fortaleza de la rodilla
KneeStrenghInjury = round(df_csv.groupby('Knee_Strength')['Injury_Current_Season'].mean()*100, 2)

KneeStrenghInjury = KneeStrenghInjury.reset_index()
KneeStrenghInjury.columns = ['Knee_Strength', 'Injured_Players']


KneeStrenghInjury = KneeStrenghInjury.sort_values(by='Injured_Players')

# px.bar() crea un gráfico de barras interactivo.
fig = px.bar(
    KneeStrenghInjury,
    x='Knee_Strength',
    y='Injured_Players',
    title='Porcentaje de jugadores lesionados según su fortaleza en la rodilla',
    labels={
        'Knee_Strength': 'Nivel de fortaleza de rodilla',
        'Injured_Players': '% Futbolistas lesionados'
    },
    color='Injured_Players',
    color_continuous_scale='Oranges',
    range_color=[0, KneeStrenghInjury['Injured_Players'].max()]
)

# fig.update_traces() pinta los porcentajes encima de las barras.
# texttemplate='%{text:,.0f}' formatea el texto con separador de miles.
# textposition='outside' coloca el texto fuera de la barra.
fig.update_traces(texttemplate='%{y:.1f}%', textposition='outside')

#fig.update_layout(template='plotly_white') pone el fondo de color blanco
#fig.update_yaxes(range=[0, 110]) pone la altura del eje Y
fig.update_layout(template='plotly_white', title_x=0.5, width=1000)
fig.update_yaxes(range=[0, 110])

fig.show()
print("Los jugadores con rodilla débil se lesionan aproximadamente 3 veces más que aquellos con rodilla fuerte, evidenciando un fuerte impacto de la fortaleza muscular en el riesgo de lesión.")

Los jugadores con rodilla débil se lesionan aproximadamente 3 veces más que aquellos con rodilla fuerte, evidenciando un fuerte impacto de la fortaleza muscular en el riesgo de lesión.

Los isquiotibiales son los músculos que más se lesionan en el fútbol. Este gráfico muestra si los jugadores con menor flexibilidad en esta zona tienen efectivamente una mayor tasa de lesión y con qué diferencia respecto a los más flexibles.

In [257]:
# Mostramos qué porcentaje de jugadores se han lesionado esta temporada en base al nivel de flexibilidad de su isquio
HamstringFlexInjury = round(df_csv.groupby('Hamstring_Flexibility_category')['Injury_Current_Season'].mean()*100, 2)

HamstringFlexInjury = HamstringFlexInjury.reset_index()
HamstringFlexInjury.columns = ['Hamstring_Flexibility_category', 'Injured_Players']


HamstringFlexInjury = HamstringFlexInjury.sort_values(by='Injured_Players')

# px.bar() crea un gráfico de barras interactivo.
fig = px.bar(
    HamstringFlexInjury,
    x='Hamstring_Flexibility_category',
    y='Injured_Players',
    title='Porcentaje de jugadores lesionados según su nivel de flexibilidad del isquio',
    labels={
        'Hamstring_Flexibility_category': 'Nivel de flexibilidad en el isquio',
        'Injured_Players': '% Futbolistas lesionados'
    },
    color='Injured_Players',
    color_continuous_scale='Greens',
    range_color=[0, HamstringFlexInjury['Injured_Players'].max()]
)

# fig.update_traces() pinta los porcentajes encima de las barras.
# texttemplate='%{text:,.0f}' formatea el texto con separador de miles.
# textposition='outside' coloca el texto fuera de la barra.
fig.update_traces(texttemplate='%{y:.1f}%', textposition='outside')

#fig.update_layout(template='plotly_white') pone el fondo de color blanco
#fig.update_yaxes(range=[0, 110]) pone la altura del eje Y
fig.update_layout(template='plotly_white', title_x=0.5, width=1000)
fig.update_yaxes(range=[0, 110])

fig.show()
print("Los jugadores con baja flexibilidad en el isquio se lesionan casi 3 veces más que aquellos con alta flexibilidad, mostrando una fuerte relación entre falta de flexibilidad y riesgo de lesión.")

Los jugadores con baja flexibilidad en el isquio se lesionan casi 3 veces más que aquellos con alta flexibilidad, mostrando una fuerte relación entre falta de flexibilidad y riesgo de lesión.

El equilibrio postural influye en la estabilidad del jugador en momentos de alto impacto. Aquí comprobamos si un peor equilibrio se traduce en más lesiones, lo que apoyaría incluir programas de prevención.

In [258]:
# Mostramos qué porcentaje de jugadores se han lesionado esta temporada en base a su equilibrio
BalanceScoreInjury = round(df_csv.groupby('Balance_score')['Injury_Current_Season'].mean()*100, 2)

BalanceScoreInjury = BalanceScoreInjury.reset_index()
BalanceScoreInjury.columns = ['Balance_score', 'Injured_Players']


BalanceScoreInjury = BalanceScoreInjury.sort_values(by='Injured_Players')

# px.bar() crea un gráfico de barras interactivo.
fig = px.bar(
    BalanceScoreInjury,
    x='Balance_score',
    y='Injured_Players',
    title='Porcentaje de jugadores lesionados según su equilibrio',
    labels={
        'Balance_score': 'Nivel de equilibrio',
        'Injured_Players': '% Futbolistas lesionados'
    },
    color='Injured_Players',
    color_continuous_scale='Purples',
    range_color=[0, BalanceScoreInjury['Injured_Players'].max()]
)

# fig.update_traces() pinta los porcentajes encima de las barras.
# texttemplate='%{text:,.0f}' formatea el texto con separador de miles.
# textposition='outside' coloca el texto fuera de la barra.
fig.update_traces(texttemplate='%{y:.1f}%', textposition='outside')

#fig.update_layout(template='plotly_white') pone el fondo de color blanco
#fig.update_yaxes(range=[0, 110]) pone la altura del eje Y
fig.update_layout(template='plotly_white', title_x=0.5, width=1000)
fig.update_yaxes(range=[0, 110])

fig.show()
print("Los jugadores con mal equilibrio se lesionan más de 3.5 veces que aquellos con buen equilibrio, evidenciando un fuerte impacto del control postural en el riesgo de lesión.")

Los jugadores con mal equilibrio se lesionan más de 3.5 veces que aquellos con buen equilibrio, evidenciando un fuerte impacto del control postural en el riesgo de lesión.

### 
<div style="box-sizing:border-box;width:95%;display:flex;align-items:center;gap:1rem;padding:.9rem 1.75rem;border-left:2px solid rgba(196,168,130,0.35);font-family:'DM Sans',sans-serif;">
  <h3 style="font-family:'Playfair Display',serif;font-size:1.5rem;font-weight:400;color:#C4A882;margin:0;padding:0;border:none;line-height:1.2;">Dimensión 4: Rendimiento neuromuscular</h3>
</div>

Los jugadores con una reacción más lenta pueden tener menos capacidad para ajustar su postura en situaciones de riesgo — una entrada, un salto, un cambio brusco. Este gráfico muestra si esa hipótesis se confirma en los datos.

In [259]:
# Mostramos qué porcentaje de jugadores se han lesionado esta temporada en base a su nivel de fortaleza de la rodilla
ReactionTimeInjury = round(df_csv.groupby('Reaction_time')['Injury_Current_Season'].mean()*100, 2)

ReactionTimeInjury = ReactionTimeInjury.reset_index()
ReactionTimeInjury.columns = ['Reaction_time', 'Injured_Players']


ReactionTimeInjury = ReactionTimeInjury.sort_values(by='Injured_Players')

# px.bar() crea un gráfico de barras interactivo.
fig = px.bar(
    ReactionTimeInjury,
    x='Injured_Players',
    y='Reaction_time',
    title='Porcentaje de jugadores lesionados según su velocidad de reacción',
    labels={
        'Reaction_time': 'Velocidad de reacción',
        'Injured_Players': '% Futbolistas lesionados'
    },
    color='Injured_Players',
    color_continuous_scale='Oranges',
    range_color=[0, ReactionTimeInjury['Injured_Players'].max()]
)

# fig.update_traces() pinta los porcentajes encima de las barras.
# texttemplate='%{text:,.0f}' formatea el texto con separador de miles.
# textposition='outside' coloca el texto fuera de la barra.
fig.update_traces(texttemplate='%{x:.1f}%', textposition='outside')

#fig.update_layout(template='plotly_white') pone el fondo de color blanco
#fig.update_yaxes(range=[0, 110]) pone la altura del eje Y
fig.update_layout(template='plotly_white', title_x=0.5, width=1000, margin=dict(l=100))
fig.update_xaxes(range=[0, 110], ticklabelstandoff=10)
fig.update_yaxes(ticklabelstandoff=10)

fig.show()
print("Los jugadores con velocidad de reacción lenta se lesionan más de 2 veces que aquellos con reacción rápida; para esta clasificación (Slow/Fast) se utilizó el percentil 50% como punto de corte.")

Los jugadores con velocidad de reacción lenta se lesionan más de 2 veces que aquellos con reacción rápida; para esta clasificación (Slow/Fast) se utilizó el percentil 50% como punto de corte.

La agilidad determina el control del cuerpo en los cambios de dirección, uno de los mecanismos de lesión más frecuentes en el fútbol. Comparamos la tasa de lesión entre jugadores de alta, media y baja agilidad.

In [260]:
# Mostramos qué porcentaje de jugadores se han lesionado esta temporada en base a su nivel de fortaleza de la rodilla
AgilityInjury = round(df_csv.groupby('Player_agility')['Injury_Current_Season'].mean()*100, 2)

AgilityInjury = AgilityInjury.reset_index()
AgilityInjury.columns = ['Player_agility', 'Injured_Players']


AgilityInjury = AgilityInjury.sort_values(by='Injured_Players')

# px.bar() crea un gráfico de barras interactivo.
fig = px.bar(
    AgilityInjury,
    x='Injured_Players',
    y='Player_agility',
    title='Porcentaje de jugadores lesionados según su agilidad',
    labels={
        'Player_agility': 'Agilidad',
        'Injured_Players': '% Futbolistas lesionados'
    },
    color='Injured_Players',
    color_continuous_scale='Greens',
    range_color=[0, AgilityInjury['Injured_Players'].max()]
)

# fig.update_traces() pinta los porcentajes encima de las barras.
# texttemplate='%{text:,.0f}' formatea el texto con separador de miles.
# textposition='outside' coloca el texto fuera de la barra.
fig.update_traces(texttemplate='%{x:.1f}%', textposition='outside')

#fig.update_layout(template='plotly_white') pone el fondo de color blanco
#fig.update_yaxes(range=[0, 110]) pone la altura del eje Y
fig.update_layout(template='plotly_white', title_x=0.5, width=1000, margin=dict(l=120))
fig.update_xaxes(range=[0, 110], ticklabelstandoff=10)
fig.update_yaxes(ticklabelstandoff=10)

fig.show()
print("Los jugadores con baja agilidad se lesionan casi 3 veces más que aquellos con alta agilidad; para definir las categorías (Poor, Moderate, High) se utilizaron los percentiles 33% y 66% como puntos de corte.")

Los jugadores con baja agilidad se lesionan casi 3 veces más que aquellos con alta agilidad; para definir las categorías (Poor, Moderate, High) se utilizaron los percentiles 33% y 66% como puntos de corte.

La velocidad de sprint genera mayores fuerzas de impacto, pero también implica mayor capacidad atlética. Este gráfico explora si existe una relación entre la velocidad máxima del jugador y su probabilidad de lesionarse.

In [267]:
# Mostramos qué porcentaje de jugadores se han lesionado esta temporada en base al número de lesiones previas
sprintSpeedInjury = round(df_csv.groupby('Sprint_Speed_km_h')['Injury_Current_Season'].mean()*100, 2)

sprintSpeedInjury = sprintSpeedInjury.reset_index()
sprintSpeedInjury.columns = ['Sprint_Speed_km_h', 'Injured_Players']

# px.bar() crea un gráfico de barras interactivo.
fig = px.bar(
    sprintSpeedInjury,
    x='Sprint_Speed_km_h',
    y='Injured_Players',
    title='Porcentaje de jugadores lesionados según su carga de entrenamiento diaria',
    labels={
        'Sprint_Speed_km_h': 'Velocidad de sprint en km/h',
        'Injured_Players': '% Futbolistas lesionados'
    },
    color='Injured_Players',
    color_continuous_scale='Purples',
    range_color=[0, sprintSpeedInjury['Injured_Players'].max()]
)

#fig.update_layout(template='plotly_white') pone el fondo de color blanco
#fig.update_yaxes(range=[0, 110]) pone la altura del eje Y
fig.update_layout(template='plotly_white', title_x=0.5)
fig.update_yaxes(range=[0, 110])

fig.show()
print("Los jugadores con menor velocidad de sprint presentan un porcentaje de lesiones significativamente mayor que los más rápidos, mostrando una relación inversa entre velocidad y riesgo de lesión. \n""Para el gráfico utilizamos la nueva variable Sprint_Speed_km_h donde convertimos de m/s a km/h para una interpretación más intuitiva y universal.")

Los jugadores con menor velocidad de sprint presentan un porcentaje de lesiones significativamente mayor que los más rápidos, mostrando una relación inversa entre velocidad y riesgo de lesión.
Para el gráfico utilizamos la nueva variable Sprint_Speed_km_h donde convertimos de m/s a km/h para una interpretación más intuitiva y universal.

### 
<div style="box-sizing:border-box;width:95%;display:flex;align-items:center;gap:1rem;padding:.9rem 1.75rem;border-left:2px solid rgba(196,168,130,0.35);font-family:'DM Sans',sans-serif;">
  <h3 style="font-family:'Playfair Display',serif;font-size:1.5rem;font-weight:400;color:#C4A882;margin:0;padding:0;border:none;line-height:1.2;">Dimensión 5: Recuperación y estilo de vida</h3>
</div>

Al igual que con la dimensión biomecánica, calculamos primero la correlación numérica entre sueño, nutrición, estrés y lesiones. Esto nos indica cuál de los tres factores tiene más peso estadístico antes de pasar a los gráficos. Interpretamos que:

- Cuando las horas de sueño aumentan, el riesgo de lesión disminuye.
- Cuando el nivel de estrés aumenta, el riesgo de lesión aumenta.
- Cuando la calidad de la nutrición aumenta, el riesgo de lesión disminuye.

In [200]:
df_csv[['Sleep_Hours_Per_Night', 'Stress_Level_Score','Nutrition_Quality_Score', 'Injury_Current_Season']].corr()

,Sleep_Hours_Per_Night,Stress_Level_Score,Nutrition_Quality_Score,Injury_Current_Season
Sleep_Hours_Per_Night,1.000000,-0.249094,0.238312,-0.510235
Stress_Level_Score,-0.249094,1.000000,-0.213145,0.529618
Nutrition_Quality_Score,0.238312,-0.213145,1.000000,-0.411951
Injury_Current_Season,-0.510235,0.529618,-0.411951,1.000000

El sueño es el principal mecanismo de recuperación del cuerpo. Este gráfico muestra si los jugadores que duermen de forma insuficiente para su edad tienen una tasa de lesión más alta que los que descansan de forma óptima.

In [266]:
# Mostramos qué porcentaje de jugadores se han lesionado esta temporada en base a su nivel de sueño (óptimo, insuficiente)
SleepInjury = round(df_csv.groupby('Sleep_category')['Injury_Current_Season'].mean()*100, 2)

SleepInjury = SleepInjury.reset_index()
SleepInjury.columns = ['Sleep_category', 'Injured_Players']

SleepInjury = SleepInjury.sort_values(by='Injured_Players')

# px.bar() crea un gráfico de barras interactivo.
fig = px.bar(
    SleepInjury,
    x='Sleep_category',
    y='Injured_Players',
    title='Porcentaje de jugadores lesionados según su nivel de sueño (descanso)',
    labels={
        'Sleep_category': 'Categoría de sueño',
        'Injured_Players': '% Futbolistas lesionados'
    },
    color='Injured_Players',
    color_continuous_scale='Purples',
    range_color=[0, SleepInjury['Injured_Players'].max()]
)

#fig.update_layout(template='plotly_white') pone el fondo de color blanco
#fig.update_yaxes(range=[0, 110]) pone la altura del eje Y
fig.update_layout(template='plotly_white', title_x=0.5)
fig.update_yaxes(range=[0, 110])

fig.show()
print(
    "Los jugadores con sueño insuficiente se lesionan casi el doble que aquellos con sueño óptimo, "
    "evidenciando el fuerte impacto del descanso en la prevención de lesiones.\n"
    "La variable utilizada es 'Sleep_category', definida según las recomendaciones "
    "de horas de sueño ajustadas por edad."
)

Los jugadores con sueño insuficiente se lesionan casi el doble que aquellos con sueño óptimo, evidenciando el fuerte impacto del descanso en la prevención de lesiones.
La variable utilizada es 'Sleep_category', definida según las recomendaciones de horas de sueño ajustadas por edad.

Este mapa de calor cruza la edad del jugador con sus horas de sueño y muestra el porcentaje de lesionados en cada combinación. Permite ver si el efecto del sueño sobre las lesiones varía según la edad, algo que el gráfico anterior no puede mostrar por sí solo.

In [268]:
# Redondeamos las horas de sueño para agrupar mejor
df_csv['Sleep_Rounded'] = df_csv['Sleep_Hours_Per_Night'].round(1)

# Calculamos el porcentaje de lesionados por edad y horas de sueño
heatmap_data = (
    df_csv.groupby(['Age', 'Sleep_Rounded'])['Injury_Current_Season']
    .mean()
    .reset_index()
)

# Convertimos a porcentaje
heatmap_data['Injury_Percentage'] = heatmap_data['Injury_Current_Season'] * 100

# Creamos el mapa de calor
fig = px.density_heatmap(
    heatmap_data,
    x='Age',
    y='Sleep_Rounded',
    z='Injury_Percentage',
    histfunc='avg',
    color_continuous_scale='YlOrRd',
    title='Porcentaje de futbolistas lesionados según edad y horas de sueño',
    labels={
        'Age': 'Edad',
        'Sleep_Rounded': 'Horas de sueño por noche',
        'Injury_Percentage': '% Futbolistas lesionados'
    }
)

fig.update_coloraxes(colorbar_title='% Futbolistas lesionados')

fig.update_layout(template='plotly_white', title_x=0.5)
fig.show()
print(
    "Se observa que, independientemente de la edad, dormir menos de 7 horas se asocia con un alto porcentaje de lesiones, "
    "mientras que dormir entre 8 y 10 horas reduce significativamente el riesgo.\n"
    "Esto refuerza la importancia del descanso adecuado como factor clave en la prevención de lesiones en todas las edades."
)

Se observa que, independientemente de la edad, dormir menos de 7 horas se asocia con un alto porcentaje de lesiones, mientras que dormir entre 8 y 10 horas reduce significativamente el riesgo.
Esto refuerza la importancia del descanso adecuado como factor clave en la prevención de lesiones en todas las edades.

Una buena alimentación es la base de la recuperación muscular. Este gráfico muestra si los jugadores con peor calidad nutricional se lesionan más, y si la mejora en la dieta tiene un efecto progresivo sobre el riesgo.

In [270]:
# Mostramos qué porcentaje de jugadores se han lesionado esta temporada en base a su nivel de sueño (óptimo, insuficiente)
NutritionInjury = round(df_csv.groupby('Nutrition_quality')['Injury_Current_Season'].mean()*100, 2)

NutritionInjury = NutritionInjury.reset_index()
NutritionInjury.columns = ['Nutrition_quality', 'Injured_Players']

NutritionInjury = NutritionInjury.sort_values(by='Injured_Players')

# px.bar() crea un gráfico de barras interactivo.
fig = px.bar(
    NutritionInjury,
    x='Nutrition_quality',
    y='Injured_Players',
    title='Porcentaje de jugadores lesionados según la calidad de su nutrición',
    labels={
        'Nutrition_quality': 'Calidad de nutrición',
        'Injured_Players': '% Futbolistas lesionados'
    },
    color='Injured_Players',
    color_continuous_scale='Greens',
    range_color=[0, NutritionInjury['Injured_Players'].max()]
)

#fig.update_layout(template='plotly_white') pone el fondo de color blanco
#fig.update_yaxes(range=[0, 110]) pone la altura del eje Y
fig.update_layout(template='plotly_white', title_x=0.5)
fig.update_yaxes(range=[0, 110])

fig.show()
print(
    "Los jugadores con peor calidad de nutrición se lesionan casi 4 veces más que aquellos con nutrición excelente, "
    "mostrando una relación clara entre alimentación y riesgo de lesión.\n"
    "Las categorías (Excellent, Good, Fair, Poor) se definieron utilizando los percentiles 25%, 50% y 75% "
    "sobre la variable 'Nutrition_Quality_Score'."
)

Los jugadores con peor calidad de nutrición se lesionan casi 4 veces más que aquellos con nutrición excelente, mostrando una relación clara entre alimentación y riesgo de lesión.
Las categorías (Excellent, Good, Fair, Poor) se definieron utilizando los percentiles 25%, 50% y 75% sobre la variable 'Nutrition_Quality_Score'.

Cerramos el análisis con el estrés. Un nivel de estrés elevado afecta la recuperación, el sueño y la concentración, todos estos factores pueden aumentar el riesgo de lesión. Este último gráfico completa el cuadro de los hábitos de vida.

In [271]:
# Mostramos qué porcentaje de jugadores se han lesionado esta temporada en base a su nivel de sueño (óptimo, insuficiente)
StressInjury = round(df_csv.groupby('Stress_level')['Injury_Current_Season'].mean()*100, 2)

StressInjury = StressInjury.reset_index()
StressInjury.columns = ['Stress_level', 'Injured_Players']

StressInjury = StressInjury.sort_values(by='Injured_Players')

# px.bar() crea un gráfico de barras interactivo.
fig = px.bar(
    StressInjury,
    x='Stress_level',
    y='Injured_Players',
    title='Porcentaje de jugadores lesionados según la nivel de estrés',
    labels={
        'Stress_level': 'Nivel de estrés',
        'Injured_Players': '% Futbolistas lesionados'
    },
    color='Injured_Players',
    color_continuous_scale='Blues',
    range_color=[0, StressInjury['Injured_Players'].max()]
)

#fig.update_layout(template='plotly_white') pone el fondo de color blanco
#fig.update_yaxes(range=[0, 110]) pone la altura del eje Y
fig.update_layout(template='plotly_white', title_x=0.5)
fig.update_yaxes(range=[0, 110])

fig.show()
print(
    "Los jugadores con alto nivel de estrés se lesionan más de 4 veces que aquellos con bajo estrés, "
    "mostrando una fuerte relación entre estrés y riesgo de lesión.\n"
    "Las categorías (Low, Medium, High) se definieron utilizando los percentiles 33% y 66% "
    "sobre la variable 'Stress_Level_Score'."
)

Los jugadores con alto nivel de estrés se lesionan más de 4 veces que aquellos con bajo estrés, mostrando una fuerte relación entre estrés y riesgo de lesión.
Las categorías (Low, Medium, High) se definieron utilizando los percentiles 33% y 66% sobre la variable 'Stress_Level_Score'.

<style>
@import url('https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400&family=DM+Sans:opsz,wght@9..40,300;9..40,400;9..40,500&display=swap');
</style>

<div style="box-sizing:border-box;width:95%;background:#2C2825;border-radius:10px;position:relative;overflow:hidden;font-family:'DM Sans',sans-serif;display:flex;align-items:center;gap:1.5rem;padding:1.6rem 2.5rem;">
  <div style="position:absolute;inset:0;background:radial-gradient(ellipse 40% 120% at 100% 50%,rgba(196,168,130,0.1) 0%,transparent 65%);pointer-events:none;"></div>
  <span style="font-family:'Playfair Display',serif;font-size:3rem;font-weight:400;color:rgba(196,168,130,0.2);line-height:1;flex-shrink:0;position:relative;z-index:1;">06</span>
  <div style="width:1px;height:36px;background:rgba(196,168,130,0.2);flex-shrink:0;position:relative;z-index:1;"></div>
  <div style="position:relative;z-index:1;">
    <p style="font-size:10px;letter-spacing:.22em;text-transform:uppercase;color:#C4A882;margin:0 0 .25rem;font-weight:500;">Conclusiones</p>
    <h2 style="font-family:'Playfair Display',serif;font-size:1.55rem;font-weight:400;color:#FAF7F2;margin:0;padding:0;border:none;line-height:1.2;">Resumen ejecutivo</h2>
  </div>
</div>

<div style="width:95%;font-family:'DM Sans',sans-serif;margin-top:.5rem;">

  <div style="display:flex;align-items:flex-start;gap:1rem;padding:.9rem 1.75rem;border-left:2px solid rgba(196,168,130,0.35);">
    <p style="font-size:15px;line-height:1.75;font-weight:300;margin:0;">El riesgo de lesión no lo determina la morfología del jugador, sino sus hábitos de recuperación y condición neuromuscular. La tasa de lesión de la muestra es del <strong style="font-weight:500;">50.1 %</strong> — 400 lesionados vs. 399 no lesionados — lo que convierte el dataset en un caso ideal para modelos de clasificación.</p>
  </div>

  <div style="display:flex;align-items:flex-start;gap:1rem;padding:.9rem 1.75rem;border-left:2px solid rgba(196,168,130,0.35);margin-top:.75rem;">
    <div style="width:100%;">
      <p style="font-size:10px;letter-spacing:.2em;text-transform:uppercase;color:#C4A882;margin:0 0 .6rem;font-weight:500;">Factores críticos — efecto multiplicador x3 a x4</p>
      <ul style="margin:0;padding:0 0 0 1.1rem;font-size:14px;font-weight:300;line-height:2;">
        <li><strong style="font-weight:500;">Estrés elevado</strong> — correlación más alta del análisis (+0.53). Más de 4× más lesiones que con estrés bajo.</li>
        <li><strong style="font-weight:500;">Nutrición deficiente</strong> — casi 4× más riesgo que con nutrición excelente (corr. −0.41).</li>
        <li><strong style="font-weight:500;">Equilibrio postural deficiente</strong> — más de 3.5× más lesiones (corr. −0.49).</li>
        <li><strong style="font-weight:500;">Historial de lesiones previas</strong> — probabilidad escala de ~25 % con 0 previas hasta ~88 % con 5.</li>
      </ul>
    </div>
  </div>

  <div style="display:flex;align-items:flex-start;gap:1rem;padding:.9rem 1.75rem;border-left:2px solid rgba(196,168,130,0.35);margin-top:.75rem;">
    <div style="width:100%;">
      <p style="font-size:10px;letter-spacing:.2em;text-transform:uppercase;color:#C4A882;margin:0 0 .6rem;font-weight:500;">Factores importantes — efecto multiplicador x2 a x3</p>
      <ul style="margin:0;padding:0 0 0 1.1rem;font-size:14px;font-weight:300;line-height:2;">
        <li><strong style="font-weight:500;">Sueño insuficiente</strong> — dobla el riesgo; correlación más alta de la dimensión de estilo de vida (−0.51).</li>
        <li><strong style="font-weight:500;">Rodilla débil e isquio poco flexible</strong> — ~3× más lesiones en ambos casos (corr. −0.45).</li>
        <li><strong style="font-weight:500;">Baja agilidad y reacción lenta</strong> — casi 3× y 2× más riesgo respectivamente.</li>
        <li><strong style="font-weight:500;">Carga de entrenamiento elevada</strong> — el riesgo sube de forma notable a partir de 2.5–3 h diarias.</li>
      </ul>
    </div>
  </div>

  <div style="display:flex;align-items:flex-start;gap:1rem;padding:.9rem 1.75rem;border-left:2px solid rgba(196,168,130,0.35);margin-top:.75rem;">
    <div style="width:100%;">
      <p style="font-size:10px;letter-spacing:.2em;text-transform:uppercase;color:#C4A882;margin:0 0 .6rem;font-weight:500;">Sin impacto determinante</p>
      <p style="margin:0;font-size:14px;font-weight:300;line-height:1.75;">Edad, altura, peso, IMC, posición en el campo y partidos disputados la temporada anterior muestran diferencias marginales entre grupos. Ninguno destaca como factor de riesgo por sí solo.</p>
    </div>
  </div>

  <div style="display:flex;align-items:flex-start;gap:1rem;padding:.9rem 1.75rem;border-left:2px solid rgba(196,168,130,0.35);margin-top:.75rem;">
    <div style="width:100%;">
      <p style="font-size:10px;letter-spacing:.2em;text-transform:uppercase;color:#C4A882;margin:0 0 .6rem;font-weight:500;">Conclusión estratégica</p>
      <p style="margin:0;font-size:14px;font-weight:300;line-height:1.75;">Las tres palancas de prevención con mayor retorno son la <strong style="font-weight:500;">gestión del estrés</strong>, la <strong style="font-weight:500;">calidad del sueño y la nutrición</strong>, y el <strong style="font-weight:500;">trabajo de fuerza y propiocepción</strong> (rodilla, isquiotibiales, equilibrio). Un modelo predictivo construido sobre estas variables tiene base sólida para intervenciones preventivas individualizadas.</p>
    </div>
  </div>

</div>

## 💯 Pruebas

In [204]:
# Saber el nutrition score del percentil 25/50/75 
print(df_csv['Nutrition_Quality_Score'].quantile(0.25))
print(df_csv['Nutrition_Quality_Score'].quantile(0.50))
print(df_csv['Nutrition_Quality_Score'].quantile(0.75))

67.80234149180306
74.35033110700118
80.49545148454833

In [205]:
# Saber el nutrition score del percentil 33/66/100
print(df_csv['Nutrition_Quality_Score'].quantile(0.33))
print(df_csv['Nutrition_Quality_Score'].quantile(0.66))

69.89002981468849
78.29982964245848

In [206]:
# Saber el height score del percentil 33/66/100
print(df_csv['Height_cm'].quantile(0.33))
print(df_csv['Height_cm'].quantile(0.66))

174.0
180.0

In [207]:
#Prueba
height1 = df_csv['Height_cm'].iloc[2]
print (height1)

if height1 < df_csv['Height_cm'].quantile(0.33):
    print('El jugador es bajito')
else: 
    print ('El jugador es alto')

172.0
El jugador es bajito

In [208]:
# Saber el weight score del percentil 33/66/100
print(df_csv['Weight_kg'].quantile(0.33))
print(df_csv['Weight_kg'].quantile(0.66))

69.0
77.68000000000006

### Paso 1:

In [209]:
#Sácame una lista que compruebe si jugadores han tenido exactamente 5 lesiones previas
df_csv['Previous_Injury_Count'] == 5

1      False
2      False
3      False
4      False
5      False
       ...
795    False
796    False
797    False
798    False
799    False
Name: Previous_Injury_Count, Length: 799, dtype: bool

### Paso 2:

In [210]:
#De la lista anterior, quédate los que su valor sea True
df_csv[ df_csv['Previous_Injury_Count'] == 5 ]

,Age,Height_cm,Weight_kg,Position,Training_Hours_Per_Week,Matches_Played_Past_Season,Previous_Injury_Count,Knee_Strength_Score,Hamstring_Flexibility,Reaction_Time_ms,...,Knee_Strength,Hamstring_Flexibility_category,Balance_score,Reaction_time,Player_agility,Sprint_Speed_km_h,Sleep_category,Stress_level,Nutrition_quality,Sleep_Rounded
48,22,186.0,88,Defender,11.668711,26,5,83.984055,79.938041,261.323940,...,Strong,Moderate,Moderate,Slow,High,21.9,Optimal,Medium,Poor,7.6
105,19,173.0,89,Midfielder,13.507599,13,5,74.673508,70.507281,240.299594,...,Medium,Low,Moderate,Fast,Poor,20.5,Insufficient,High,Fair,7.6
170,24,187.0,72,Forward,11.318649,30,5,71.121162,77.369860,242.555174,...,Weak,Moderate,High,Fast,Poor,20.4,Insufficient,High,Good,6.5
259,18,186.0,79,Defender,13.131082,20,5,62.876995,76.662631,281.508270,...,Weak,Moderate,Poor,Slow,High,20.6,Insufficient,High,Good,5.7
266,19,181.0,56,Defender,10.642220,39,5,81.257576,66.802015,237.444094,...,Strong,Low,Poor,Fast,Moderate,20.5,Insufficient,High,Fair,7.5
289,21,178.0,65,Midfielder,13.307167,18,5,78.044684,64.868638,249.743710,...,Strong,Low,Poor,Slow,Moderate,20.2,Optimal,Medium,Good,8.1
395,18,176.0,80,Defender,13.481250,18,5,78.053813,67.688324,247.883810,...,Strong,Low,Poor,Fast,Poor,20.0,Optimal,High,Poor,8.5
396,19,179.0,68,Defender,9.051812,23,5,75.466815,84.830420,257.009935,...,Medium,High,High,Slow,Moderate,22.3,Insufficient,Low,Good,8.0
404,20,178.0,76,Defender,13.898503,25,5,82.882702,64.313230,260.973860,...,Strong,Low,Moderate,Slow,Poor,21.7,Optimal,High,Good,8.0
433,22,180.0,76,Forward,5.668266,22,5,69.696656,82.339014,204.914816,...,Weak,High,Poor,Fast,Moderate,21.0,Insufficient,High,Fair,6.1
490,24,180.0,75,Midfielder,10.580934,38,5,77.483054,86.029007,257.842552,...,Strong,High,Poor,Slow,High,21.5,Insufficient,Medium,Fair,6.5
545,20,172.0,73,Goalkeeper,8.520433,38,5,60.903645,72.749399,247.067102,...,Weak,Low,Moderate,Fast,Poor,20.9,Optimal,Medium,Poor,8.1
605,20,170.0,78,Defender,10.132313,27,5,84.453050,90.519342,268.096957,...,Strong,High,Moderate,Slow,High,21.0,Insufficient,Medium,Fair,7.0
681,19,167.0,51,Midfielder,5.000000,30,5,69.144781,75.352867,254.274852,...,Weak,Low,Poor,Slow,Poor,22.7,Optimal,High,Good,8.2
687,24,172.0,76,Goalkeeper,13.298849,31,5,76.372432,83.150547,227.001613,...,Medium,High,Poor,Fast,Poor,21.2,Insufficient,High,Excellent,6.0
700,20,172.0,57,Defender,5.590822,23,5,70.286926,66.978183,286.048694,...,Weak,Low,Poor,Slow,Moderate,20.7,Insufficient,Medium,Fair,7.8
780,18,178.0,67,Defender,9.528516,23,5,69.405815,83.023340,283.026432,...,Weak,High,High,Slow,Moderate,20.8,Insufficient,High,Fair,7.2

### Paso 3:

In [211]:
#Ahora, para esos jugadores que sabemos que han tenido exactament 5 lesiones, sácame el valor de su columna 'Injured_Current_Season'
df_csv[ df_csv['Previous_Injury_Count'] == 5 ] ['Injury_Current_Season']

48     False
105     True
170     True
259     True
266     True
289     True
395     True
396    False
404     True
433     True
490     True
545     True
605     True
681     True
687     True
700     True
780     True
Name: Injury_Current_Season, dtype: bool

### Paso 4:

In [212]:
#Finalmente, para esos jugadores que sabemos que han tenido exactament 5 lesiones, cuenta cuantos son True y cuantos son False
df_csv[ df_csv['Previous_Injury_Count'] == 5 ] ['Injury_Current_Season'].value_counts()

Injury_Current_Season
True     15
False     2
Name: count, dtype: int64

In [213]:
from plotly.subplots import make_subplots

# 🔹 1. Calculamos el porcentaje de lesión
percentageInjury = df_csv.groupby('Previous_Injury_Count')['Injury_Current_Season'].mean() * 100

# Convertimos a DataFrame
percentageInjury = percentageInjury.reset_index()
percentageInjury.columns = ['Previous_Injury_Count', 'Injury_Percentage']

# 🔹 2. Creamos la gráfica original
fig_bar = px.bar(
    percentageInjury,
    x='Previous_Injury_Count',
    y='Injury_Percentage',
    labels={
        'Previous_Injury_Count': 'Número de lesiones previas',
        'Injury_Percentage': 'Probabilidad de lesión (%)'
    }
)

fig_bar.update_traces(
    texttemplate='%{y:.1f}%',
    textposition='outside'
)

# 🔹 3. Creamos el grid 2x2
fig = make_subplots(
    rows=2,
    cols=2,
    subplot_titles=(
        "Probabilidad de lesión", "", 
        "", ""
    )
)

# 🔹 4. Añadimos la gráfica en [0,0] → (row=1, col=1)
fig.add_trace(
    fig_bar.data[0],
    row=2,
    col=2
)

# 🔹 5. Añadimos títulos de ejes (IMPORTANTE)
fig.update_xaxes(
    title_text="Número de lesiones previas",
    row=2,
    col=2
)

fig.update_yaxes(
    title_text="Probabilidad de lesión (%)",
    range=[0, 110],  # para que no se corten los %
    row=2,
    col=2
)

# 🔹 6. Layout final
fig.update_layout(
    height=700,
    width=900,
    template='plotly_white',
    showlegend=False
)

# 🔹 7. Mostrar
fig.show()